Add repeated protocols in protocol_config for direct reach and frequency measurement
world-federation-of-advertisers/cross-media-measurement-api pull request #114
Opened 2022-10-11 16:49 UTC by iverson52000

2022-10-11 16:59 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE6yoHY0mAB8G1q_veT:-NE6yoHY0mAB8G1q_veU:b-utrngs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ad185db20393f2afedd5d70127a1fb8563b90d02/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L63)):*
> ```protobuf
>   // `REACH_AND_FREQUENCY`)
>   //
>   // Otherwise, if this is not set or protocols list has direct protocol, the
> ```

The idea is that this would now always be set, including for volumetric measurements. Those would just always have a protocol of "direct".



_Code quote:_
```protobuf
 if this is not set or
```


<!-- Sent from Reviewable.io -->

2022-10-11 17:07 UTC, iverson52000 commented
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE6yoHY0mAB8G1q_veT:-NE6zvMK1LpW5H4_-ZH-:bf6uq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ad185db20393f2afedd5d70127a1fb8563b90d02/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The idea is that this would now always be set, including for volumetric measurements. Those would just always have a protocol of "direct".
</blockquote></details>

Oh you mean protocolConfig now has to be generated for impression and duration as well? I have to try since I feel it would require more changes


<!-- Sent from Reviewable.io -->

2022-10-11 19:51 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE6yoHY0mAB8G1q_veT:-NE7aUDw6-yCn-7AZvFu:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ad185db20393f2afedd5d70127a1fb8563b90d02/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L63)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Oh you mean protocolConfig now has to be generated for impression and duration as well? I have to try since I feel it would require more changes
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-10-11 20:20 UTC, matthewclegg approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @robinsons, @SanjayVas, and @xnegron)



<!-- Sent from Reviewable.io -->

2022-10-11 22:23 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @rmirisola, @robinsons, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE87xUx2dY-NRC6teZ3:-NE87xUyDS-78FY3nt5X:b-iataao) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0f7bc53604c945be21abcd92585c2084c5746744/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L40)):*
> ```protobuf
>   // The values should correspond to the fields in the `measurement_type` Oneof
>   // in `MeasurementSpec`.
>   enum MeasurementType {
> ```

We'll at least need to keep this for a bit for backwards-compatibility, but do we need it going forward when it matches 1:1 with `measurement_type` from `MeasurementSpec`?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE870F36nnNB-tdMF5a:-NE870F43m0On-TjAwhE:b-cspba0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0f7bc53604c945be21abcd92585c2084c5746744/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L59)):*
> ```protobuf
>   // Denormalized `protocol_config` field from `measurement`. Immutable.
>   //
>   // If protocols list in protocol_config has protocol other than direct, the
> ```

Let's drop all this and put the documentation on the relevant fields in Protocol. e.g. document that the direct protocol means calling `Requisitions/FulfillDirectRequisition` and document that LLv2 protocol means calling `RequisitionFulfillment/FulfillRequisition` with an encrypted sketch.



_Code quote:_
```protobuf
  //
  // If protocols list in protocol_config has protocol other than direct, the
  // requisition can be fulfilled by calling
  // RequisitionFulfillment/FulfillRequisition(`measurement_type` is
  // `REACH_AND_FREQUENCY`)
  //
  // Otherwise, if protocols list has or only has direct protocol, the
  // Requisition is considered "direct" and can be fulfilled by calling
  // Requisitions/FulfillDirectRequisition (volumetric measurement -
  // `measurement_type` is `IMPRESSION`/`DURATION` or direct reach and frequency
```


<!-- Sent from Reviewable.io -->

2022-10-12 16:44 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 2 unresolved discussions (waiting on @rmirisola, @robinsons, @SanjayVas, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE87xUx2dY-NRC6teZ3:-NEC2yObDQ4BX9dG588m:bxhzksf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0f7bc53604c945be21abcd92585c2084c5746744/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We'll at least need to keep this for a bit for backwards-compatibility, but do we need it going forward when it matches 1:1 with `measurement_type` from `MeasurementSpec`?
</blockquote></details>

I guess yes because this is being used when converting internal to public `ProtocolConfig`?
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/728/files#diff-5041a4afec93920965b3804e92a6651edea0416cd54c933ff94bf2dbeaca48c0R147


<!-- Sent from Reviewable.io -->

2022-10-12 16:57 UTC, iverson52000 commented
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE870F36nnNB-tdMF5a:-NEC7CCo96IbR9sCkgDx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0f7bc53604c945be21abcd92585c2084c5746744/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's drop all this and put the documentation on the relevant fields in Protocol. e.g. document that the direct protocol means calling `Requisitions/FulfillDirectRequisition` and document that LLv2 protocol means calling `RequisitionFulfillment/FulfillRequisition` with an encrypted sketch.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-12 18:48 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @matthewclegg, @rmirisola, @robinsons, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 82 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NECVK_YEYA-O4oCR92h:-NECVK_YEYA-O4oCR92i:baky2hb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c0cdbd29082f9c1ebc0414c8aeb36f846cc89c50/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L82)):*
> ```protobuf
>       LiquidLegionsV2 liquid_legions_v2 = 1;
> 
>       // direct can be fulfilled by calling
> ```

nit: start the documentation of a field or message type with a [summary fragment](https://developer.android.com/kotlin/style-guide#summary_fragment) the same way we do in Kotlin, with a blank line preceding any optional detail paragraphs.

e.g.

```proto
// Direct protocol.
//
// The Requisition can be fulfilled by calling ...
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 85 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NECUjyC8LXZ6EuDMHKg:-NECUjyC8LXZ6EuDMHKh:bb2g6mh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c0cdbd29082f9c1ebc0414c8aeb36f846cc89c50/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L85)):*
> ```protobuf
>       // Requisitions/FulfillDirectRequisition
>       // (volumetric measurement - `measurement_type` is `IMPRESSION`/`DURATION`
>       // or direct reach and frequency measurement - measurement_type` is
> ```

Drop this info from here and instead update the documentation of `FulfillDirectRequisitionRequest` to be more explicit about what data should be inside the `SignedData`. I assume it's a serialized `Measurement.Result` message?



_Code quote:_
```protobuf
      // (volumetric measurement - `measurement_type` is `IMPRESSION`/`DURATION`
      // or direct reach and frequency measurement - measurement_type` is
      // `REACH_AND_FREQUENCY` and it only has single DataProvider)
```


<!-- Sent from Reviewable.io -->

2022-10-12 20:16 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg, @rmirisola, @robinsons, @SanjayVas, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NE87xUx2dY-NRC6teZ3:-NECpfyPC5ZosrdX1CS-:b40m9b1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0f7bc53604c945be21abcd92585c2084c5746744/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Right, but we could theoretically change the internal protocol config format (though we probably shouldn't for stability reasons) to not have that field or pull the info in from the parent MeasurementSpec during the conversion.

Regardless, nothing we need to do now. Just musing on whether we have duplicate info in the API now.
</blockquote></details>

Got it. Thanks for the clarification


<!-- Sent from Reviewable.io -->

2022-10-12 20:30 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @matthewclegg, @rmirisola, @robinsons, @SanjayVas, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 85 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NECUjyC8LXZ6EuDMHKg:-NECskCvB4cJ0J42fayg:b4c4juq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c0cdbd29082f9c1ebc0414c8aeb36f846cc89c50/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L85)):*
Yes
> I assume it's a serialized Measurement.Result message?


<!-- Sent from Reviewable.io -->

2022-10-12 21:04 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg, @rmirisola, @robinsons, and @xnegron)



<!-- Sent from Reviewable.io -->

2022-10-12 21:27 UTC, robinsons approved these changes
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @matthewclegg, @rmirisola, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 95 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NED4dSl5z9wW_w3Vjv3:-NED4dSl5z9wW_w3Vjv4:b-idvifa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6836b52090470da015edff3e825b5231c0025e7/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L95)):*
> ```protobuf
>     //
>     // May only be set when `measurement_type` is `REACH_AND_FREQUENCY`.
>     LiquidLegionsV2 liquid_legions_v2 = 3 [deprecated = true];
> ```

nit: Since the field is deprecated, can we indicate in the comment what the replacement is?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisitions_service.proto` line 106 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NED55Nw5j4LG7xMUbbB:-NED55Nw5j4LG7xMUbbC:b2kpdcv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6836b52090470da015edff3e825b5231c0025e7/src/main/proto/wfa/measurement/api/v2alpha/requisitions_service.proto#L106)):*
> ```protobuf
>       [(google.api.resource_reference).type = "halo.wfanet.org/Requisition"];
> 
>   // Encrypted `SignedData` containing the data(serialized Measurement.Result
> ```

nit: Add a space between "data" and "(serialized".


<!-- Sent from Reviewable.io -->

2022-10-13 14:49 UTC, matthewclegg approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @rmirisola, @stevenwarejones, and @xnegron)



<!-- Sent from Reviewable.io -->

2022-10-13 16:58 UTC, robinsons approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHGpEA-xoth9b2lJOo:-NEHGpEBD-z3Wt1Pnvfg:b-bgb6aa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7080bf1e64942d9961a1b6ca919acd1369cf316b/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L95)):*
> ```protobuf
>     //
>     // May only be set when `measurement_type` is `REACH_AND_FREQUENCY`.
>     // Deprecated and replace with protocols
> ```

nit: Add a full stop (period) at the end, and include an empty comment line between paragraphs (even if those "paragraphs" are just one sentence).


<!-- Sent from Reviewable.io -->

2022-10-13 17:02 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @rmirisola, @robinsons, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHGpEA-xoth9b2lJOo:-NEHHkUr7wiGa9kNHHpJ:bdxt7qo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7080bf1e64942d9961a1b6ca919acd1369cf316b/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L95)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: Add a full stop (period) at the end, and include an empty comment line between paragraphs (even if those "paragraphs" are just one sentence).
</blockquote></details>

Thanks for the reminder. I always forget to add period


<!-- Sent from Reviewable.io -->

2022-10-13 17:09 UTC, robinsons approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)



<!-- Sent from Reviewable.io -->

2022-10-13 18:15 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @rmirisola, @robinsons, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEHY-t32k0yHYDOvzr4:bjl0cxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
> ```protobuf
>     MEASUREMENT_TYPE_UNSPECIFIED = 0;
>     REACH_AND_FREQUENCY = 1;
>     IMPRESSION = 2;
> ```

I think I must be misunderstanding something. I thought any measurement without protocolConfig set was automatically a direct measurement.
See: https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4b834122ac50c62c96c45e60304c7fd8d3db2f0b/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L59

Are you wanting to add this so that direct measurements can still be fulfilled to mpc workers?


<!-- Sent from Reviewable.io -->

2022-10-13 19:54 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEHrmaa9KcgT_B4D_k-:bm5e6m0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
>  I thought any measurement without protocolConfig set was automatically a direct measurement.

Yes we are changing this approach because it may be more flexible for EDP to choose to do direct or MPC-based R/F calculation for single EDP measurement . 
The new approach is that a new repeated field `protocols` is created. And for different measurement type:

REACH_AND_FREQUENCY(multiple EDPs) => protocols: [liquid_legions_v2]
REACH_AND_FREQUENCY(single EDP) => protocols: [liquid_legions_v2, direct]
IMPRESSION, DURATION => protocols: [direct]

The old `oneof protocol` will be deprecated


<!-- Sent from Reviewable.io -->

2022-10-13 21:05 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEHgOmgDo_B1V7TZ75c:b-iwb3q5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

>  I thought any measurement without protocolConfig set was automatically a direct measurement.

Yes we are changing this approach because it may be more flexible for EDP to choose to do direct or MPC-based R/F calculation for single EDP measurement . 
The new approach is that a new repeated field `protocols` is created. And for different measurement type:

REACH_AND_FREQUENCY(multiple EDPs) => protocols: [liquid_legions_v2]
REACH_AND_FREQUENCY(single EDP) => protocols: [liquid_legions_v2, direct]
IMPRESSION, DURATION => protocols: [direct]

The old `oneof protocol` will be deprecated
</blockquote></details>

This is specifically changing the API such that ProtocolConfig is always set and  "direct" is it's own protocol.


<!-- Sent from Reviewable.io -->

2022-10-13 21:58 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @rmirisola, @SanjayVas, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEILWPG-thW45SWNfAp:bh3zvg0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is specifically changing the API such that ProtocolConfig is always set and  "direct" is it's own protocol.
</blockquote></details>

whats the benefit of this approach? I question if we should even allow single edp measurements to get submitted with liquid_legions_v2. What is the use case?


<!-- Sent from Reviewable.io -->

2022-10-13 22:14 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEIOO8VEOSjsjh5HT_q:b-c86mjl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the benefit of this approach? I question if we should even allow single edp measurements to get submitted with liquid_legions_v2. What is the use case?
</blockquote></details>

The main benefit of this approach is that what the EDP should do is more explicit in the API (e.g. which method they should call to fulfill). The secondary benefit is that it allows the flexibility of having the Kingdom specify multiple protocols and letting the EDP choose.

The latter is immediately useful to give some breathing room for current EDP implementors to add support for direct R/F. Note that what protocols are allowed is decided by the Kingdom, so we can easily drop LLv2 for single-EDP measurements without future changes to this API.


<!-- Sent from Reviewable.io -->

2022-10-14 15:09 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @rmirisola, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEM1Q0d8KA36lMPAHxr:ba35ixy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The main benefit of this approach is that what the EDP should do is more explicit in the API (e.g. which method they should call to fulfill). The secondary benefit is that it allows the flexibility of having the Kingdom specify multiple protocols and letting the EDP choose.

The latter is immediately useful to give some breathing room for current EDP implementors to add support for direct R/F. Note that what protocols are allowed is decided by the Kingdom, so we can easily drop LLv2 for single-EDP measurements without future changes to this API.
</blockquote></details>

what is the mpc burden for fulfilling this way? I'm a little concerned with giving options that might raise the cost of the system unnecessarily.


<!-- Sent from Reviewable.io -->

2022-10-14 17:03 UTC, SanjayVas approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEMQRmfE41LvH9yKPox:bpjfnh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is the mpc burden for fulfilling this way? I'm a little concerned with giving options that might raise the cost of the system unnecessarily.
</blockquote></details>

It should be no different than any other R/F measurement for the MPC.

I want to be clear that this PR is just for the API changes which clean things up in terms of clarity and add a little flexibility. How that flexibility is used is being implemented in #728. I'd recommend moving the discussion there.


<!-- Sent from Reviewable.io -->

2022-10-17 12:55 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @rmirisola, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEa-W3s3jHVerKylFvK:b-5b0ohf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It should be no different than any other R/F measurement for the MPC.

I want to be clear that this PR is just for the API changes which clean things up in terms of clarity and add a little flexibility. How that flexibility is used is being implemented in #728. I'd recommend moving the discussion there.
</blockquote></details>

I'd argue the discussion should take place on the API level. 

"It should be no different than any other R/F measurement for the MPC."
Isn't this more expensive for the mpc workers to calculate than for an edp?

A change like this also reduces the privacy of direct measurements as the sketches are revealed to the initial mpc worker.


<!-- Sent from Reviewable.io -->

2022-10-18 17:23 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEg3qP33CZ-vPMv-0Qo:bcqfac4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
> I'd argue the discussion should take place on the API level.

The distinction I was making is that I believe most of this API change is positive even if we don't use it to allow EDPs any additional choice for R/F measurements. Considering `Direct` to be a protocol makes things clearer in terms of an EDP figuring out what they should do rather than having more complex logic around measurement type and whether ProtocolConfig was set. The only part of this API change that may not be used if we don't decide to allow EDP choice for R/F measurements is making `protocols` repeated. Hence why I believe the discussion of that belongs in #728.

Just to reply to what is here though, we would prefer that EDPs to move to direct fulfillment for single-EDP R/F measurements for the reasons you've stated. This may just be a temporary option.


<!-- Sent from Reviewable.io -->

2022-10-19 16:50 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @rmirisola, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEl6z7kCGXDXm8OzuxD:b-52y7yg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I'd argue the discussion should take place on the API level.

The distinction I was making is that I believe most of this API change is positive even if we don't use it to allow EDPs any additional choice for R/F measurements. Considering `Direct` to be a protocol makes things clearer in terms of an EDP figuring out what they should do rather than having more complex logic around measurement type and whether ProtocolConfig was set. The only part of this API change that may not be used if we don't decide to allow EDP choice for R/F measurements is making `protocols` repeated. Hence why I believe the discussion of that belongs in #728.

Just to reply to what is here though, we would prefer that EDPs to move to direct fulfillment for single-EDP R/F measurements for the reasons you've stated. This may just be a temporary option.
</blockquote></details>

hmmm... I'm just wondering if the API should prevent combining Direct and MPC protocols as options.
```
message MpcProtocol {
   oneof mpc_protocol {
       LiquidLegionsV2 liquid_legions_v2 = 1;
   }
}

message MpcProtocols {
   repeated MpcProtocol mpc_protocol = 1
}

oneof protocols {
   DirectProtocols direct_protocols = 1
   MpcProtocols mpc_protocols = 2
}
```


<!-- Sent from Reviewable.io -->

2022-10-19 21:55 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: all files reviewed, 1 unresolved discussion (waiting on @rmirisola, @stevenwarejones, and @xnegron)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114#-NEHY-t32k0yHYDOvzr3:-NEmDcRv65w2qfuhXENh:bi159la) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7d64423f0da958284de9d3ca588f42ea837437f/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

hmmm... I'm just wondering if the API should prevent combining Direct and MPC protocols as options.
```
message MpcProtocol {
   oneof mpc_protocol {
       LiquidLegionsV2 liquid_legions_v2 = 1;
   }
}

message MpcProtocols {
   repeated MpcProtocol mpc_protocol = 1
}

oneof protocols {
   DirectProtocols direct_protocols = 1
   MpcProtocols mpc_protocols = 2
}
```
</blockquote></details>

The API is being designed for flexibility, including the flexibility of allowing the EDP to choose between MPC and direct. We don't want to prevent this at the API level, and in fact want to use this flexibility at least temporarily (though that latter part is more of a business decision).

I furthermore don't think we need to make the distinction between MPC and non-MPC protocols, especially as we don't want to restrict ourselves in terms of what kind of protocols we might support in the future.


<!-- Sent from Reviewable.io -->

2022-10-21 15:22 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r3, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rmirisola and @xnegron)



<!-- Sent from Reviewable.io -->

2022-10-24 18:26 UTC, merged