Add EdpComputation
world-federation-of-advertisers/cross-media-measurement-api pull request #163
Opened 2023-07-18 22:37 UTC by riemanli

2023-07-18 22:37 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)
<!-- Reviewable:end -->

2023-07-18 22:37 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #163** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement-api/163" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement-api/163?utm_source=stack-comment).

2023-07-18 22:59 UTC, SanjayVas reviewed
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fD2UbE4ePraeFwqo5:-N_fD2UbE4ePraeFwqo6:brmd0if) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L163)):*
> ```proto
>     //
>     // Only set when the measurement is Direct.
>     ProtocolConfig.EdpComputation edp_direct_computation = 5;
> ```

I thought we wanted a separate methodology submessage for each submessage of Response. e.g. Impression has different possible methodologies than Reach. This might mean some duplication between Reach and Frequency, but this is necessary to allow them to diverge.

@kungfucraig is that more aligned with what you were thinking?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fCl4aEZcxmEQiEkJs:-N_fCl4bEFVDuwmHRD_g:bctnpx6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L100)):*
> ```proto
> 
>   // Contains different options for EDP computation.
>   message EdpComputation {
> ```

We don't use the "EDP" abbreviation anywhere in the public API. We instead refer to `DataProvider`.



_Code quote:_
```proto
  // Contains different options for EDP computation.
  message EdpComputation {
```


<!-- Sent from Reviewable.io -->

2023-07-18 23:05 UTC, kungfucraig requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fCl4aEZcxmEQiEkJs:-N_fEM1rDqyZTfdp6B-N:b-8637hu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't use the "EDP" abbreviation anywhere in the public API. We instead refer to `DataProvider`.
</blockquote></details>

Maybe call this DirectComputation? And have a "oneof" for each Measurement Type? And then for each Measurement Type a message with another oneof that shows the valid computation methods?

I don't think we want to use the LLV2 from the MPC because we are bringing along MPC only params (e.g. elliptic curve ID). SketchParams seems + max frequency seems adequate.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fEAtP46al5_v_YcsN:-N_fEAtP46al5_v_YcsO:b-u82ci9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L117)):*
> ```proto
>   // Configuration for the Direct protocol.
>   message Direct {
>     // The recommended computation to EDP. EDP may choose different computation
> ```

I think NoiseMechanism goes directly under "Direct" vs. embedded in each measurement type.


<!-- Sent from Reviewable.io -->

2023-07-19 00:16 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fD2UbE4ePraeFwqo5:-N_fUrCVC-Ii4pn6nGCL:b6nswyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L163)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought we wanted a separate methodology submessage for each submessage of Response. e.g. Impression has different possible methodologies than Reach. This might mean some duplication between Reach and Frequency, but this is necessary to allow them to diverge.

@kungfucraig is that more aligned with what you were thinking?
</blockquote></details>

I split the methodologies by measurement types. I wonder if we still need to have methodology submessage for each measurement type in this case.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fCl4aEZcxmEQiEkJs:-N_fUpt59v4zD8UQPrGl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L100)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Maybe call this DirectComputation? And have a "oneof" for each Measurement Type? And then for each Measurement Type a message with another oneof that shows the valid computation methods?

I don't think we want to use the LLV2 from the MPC because we are bringing along MPC only params (e.g. elliptic curve ID). SketchParams seems + max frequency seems adequate.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fEAtP46al5_v_YcsN:-N_fUqXk-koUUq4CAfOn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L117)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think NoiseMechanism goes directly under "Direct" vs. embedded in each measurement type.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-19 17:15 UTC, SanjayVas reviewed
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @jiayu-google and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fD2UbE4ePraeFwqo5:-N_j83487T-Cln3nxdwy:b-h8ywwq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L163)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I split the methodologies by measurement types. I wonder if we still need to have methodology submessage for each measurement type in this case.
</blockquote></details>

My thought was inverting the structure. Right now you have a single message for all direct measurements, with a oneof based on measurement type. What I was thinking was separate messages for each measurement type, with a oneof for the different methodologies.


<!-- Sent from Reviewable.io -->

2023-07-19 17:18 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_j8xOv01ph6DqjbJSE:-N_j8xOv01ph6DqjbJSF:b-yzewws) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L100)):*
> ```proto
> 
>   // Contains different options for EDP computation.
>   message EdpComputation {
> ```

This includes the options of `DataProviderReachAndFrequencyComputation`. Do you plan to have a separate message of `DataProviderImpressionComputation` later?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 110 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_irYGV45d3JrsWLjpl:-N_irYGV45d3JrsWLjpm:bnh6jve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L110)):*
> ```proto
>       // May only be set when the measurement type is REACH_AND_FREQUENCY or
>       // REACH. `Requisition`s using this protocol can be fulfilled by calling
>       // RequisitionFulfillment/FulfillRequisition with an encrypted sketch.
> ```

This line seems to be copied from the comment about `LiquidLegionsV2` in `protocol_config`,

As we discussed yesterday, here in EDP computation we don't need all the fields of `LiquidLegionsV2` such as `data_provider_noise`. We only need the field `sketch_params`. And EDP doesn't have to "encrypt" the sketch. So, this line of comment is not precise. 
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_j6Cae3McHW5n-p-xu:-N_j6Cae3McHW5n-p-xv:bsjt4us) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L111)):*
> ```proto
>       // REACH. `Requisition`s using this protocol can be fulfilled by calling
>       // RequisitionFulfillment/FulfillRequisition with an encrypted sketch.
>       LiquidLegionsV2 liquid_legions_v2 = 2;
> ```

Following the above comment, consider:
`LiquidLegionsV2SketchParams liquid_legion_v2 _sketch_params = 2`


<!-- Sent from Reviewable.io -->

2023-07-19 17:32 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_j6Cae3McHW5n-p-xu:-N_jBaaC7wnVdcpKWdbz:bxkwlcm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L111)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Following the above comment, consider:
`LiquidLegionsV2SketchParams liquid_legion_v2 _sketch_params = 2`
</blockquote></details>

Sorry, have to add more complexity here:) 

In EDP computation, I don't expect EDPs to use LiquidLegionsV2 exactly follow the Halo implementation world-federation-of-advertisers/any-sketch/src/main/cc. I think we should trust that EDP implemented their own sketch and estimator correctly. That said, we can, and probably should provide a simple reference implementation (maybe just in python) with test cases for EDPs to check.


<!-- Sent from Reviewable.io -->

2023-07-19 22:14 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_fD2UbE4ePraeFwqo5:-N_kCE7H1PkPTw61cTcv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L163)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My thought was inverting the structure. Right now you have a single message for all direct measurements, with a oneof based on measurement type. What I was thinking was separate messages for each measurement type, with a oneof for the different methodologies.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_j8xOv01ph6DqjbJSE:-N_kCZmO2k6oSAwBg7s3:b2cj13b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L100)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

This includes the options of `DataProviderReachAndFrequencyComputation`. Do you plan to have a separate message of `DataProviderImpressionComputation` later?
</blockquote></details>

Please see the latest changes in `direct_computation.proto`
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 110 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_irYGV45d3JrsWLjpl:-N_kCGzjAkPAJCqFHokG:b2cj13b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L110)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

This line seems to be copied from the comment about `LiquidLegionsV2` in `protocol_config`,

As we discussed yesterday, here in EDP computation we don't need all the fields of `LiquidLegionsV2` such as `data_provider_noise`. We only need the field `sketch_params`. And EDP doesn't have to "encrypt" the sketch. So, this line of comment is not precise. 
</blockquote></details>

Please see the latest changes in `direct_computation.proto`
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_j6Cae3McHW5n-p-xu:-N_kCljK3uIx3FuseuB7:bwdgryw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e6f674995778791888fa380cc32a25eb6b24fbf1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L111)):*
> Following the above comment, consider:  
> `LiquidLegionsV2SketchParams liquid_legion_v2 _sketch_params = 2`

Please see the latest changes in `direct_computation.proto`

> Sorry, have to add more complexity here:)
> 
> In EDP computation, I don't expect EDPs to use LiquidLegionsV2 exactly follow the Halo implementation world-federation-of-advertisers/any-sketch/src/main/cc. I think we should trust that EDP implemented their own sketch and estimator correctly. That said, we can, and probably should provide a simple reference implementation (maybe just in python) with test cases for EDPs to check.

I think that is probably out of scope for this PR.


<!-- Sent from Reviewable.io -->

2023-07-19 22:47 UTC, SanjayVas reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_kJeNR2AFIMU5fnoio:btj2jjn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
> ```proto
> message DirectLiquidLegionsV2 {
>   // Parameters for the direct Liquid Legions sketch.
>   message DirectLiquidLegionsSketchParams {
> ```

These doesn't look any different than [`LiquidLegionsSketchParams`](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7ea37444b0e0e4407202709aaef5fe6c20030a3/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L161). Are we expecting the "direct" parameters to diverge?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kKA4a2H8T1tdABb5V:-N_kKA4a2H8T1tdABb5W:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L159)):*
> ```proto
>       // The computation methodology done by data provider.
>       oneof methodology {
>         // Deterministic count distinct option.
> ```

nit



_Suggestion:_
```proto
methodology
```


<!-- Sent from Reviewable.io -->

2023-07-19 23:09 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_kMwgM8SG1sdsjmeoI:bp2et51) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These doesn't look any different than [`LiquidLegionsSketchParams`](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7ea37444b0e0e4407202709aaef5fe6c20030a3/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L161). Are we expecting the "direct" parameters to diverge?
</blockquote></details>

My thought is that since `ReachOnlyLiquidLegionsSketchParams` already differs from `LiquidLegionsSketchParams`, it's possible we will have different setup for the direct LLV2 in the future. @jiayu-google could you help answer this question?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kKA4a2H8T1tdABb5V:-N_kMcFzDpe_10M0BzaO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-20 16:25 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_o5ono05QSLrLsttGq:b-v710er) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

My thought is that since `ReachOnlyLiquidLegionsSketchParams` already differs from `LiquidLegionsSketchParams`, it's possible we will have different setup for the direct LLV2 in the future. @jiayu-google could you help answer this question?
</blockquote></details>

good question.
1. the only difference between `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams` is that `ReachOnlyLiquidLegionsSketchParams` drops the `sampling_indicator_size`, i.e., fingerprint size that is only used in frequency estimation.
2. I don't expect `DirectLiquidLegionsSketchParams` to diverge from both `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams`


<!-- Sent from Reviewable.io -->

2023-07-20 16:26 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_o6nDbD8ofWNp4u6zL:bf6rtyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

good question.
1. the only difference between `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams` is that `ReachOnlyLiquidLegionsSketchParams` drops the `sampling_indicator_size`, i.e., fingerprint size that is only used in frequency estimation.
2. I don't expect `DirectLiquidLegionsSketchParams` to diverge from both `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams`
</blockquote></details>

I mean I don't expect `DirectLiquidLegionsSketchParams` to diverge from both `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams` even in LLv3, 4, ...


<!-- Sent from Reviewable.io -->

2023-07-20 16:41 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_o9Ba4BByJlQtgg0Ge:b-77h1sj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

I mean I don't expect `DirectLiquidLegionsSketchParams` to diverge from both `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams` even in LLv3, 4, ...
</blockquote></details>

By diverge, I think we mean the messages contain different fields. For example, `ReachOnlyLiquidLegionsSketchParams` has `decay_rate` and `max_size` while `LiquidLegionsSketchParams` has an additional field `sampling_indicator_size`.


<!-- Sent from Reviewable.io -->

2023-07-20 16:44 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_oAko9EUWyEkEpTGvW:bjsu7m7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

By diverge, I think we mean the messages contain different fields. For example, `ReachOnlyLiquidLegionsSketchParams` has `decay_rate` and `max_size` while `LiquidLegionsSketchParams` has an additional field `sampling_indicator_size`.
</blockquote></details>

Yes. I mean `DirectLiquidLegionsSketchParams`is always expected to be either `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams`. In fact,  `DirectReachOnlyLiquidLegionsSketchParams`always = `ReachOnlyLiquidLegionsSketchParams`, `DirectReachAndFrequencyLiquidLegionsSketchParams`always = `LiquidLegionsSketchParams`.


<!-- Sent from Reviewable.io -->

2023-07-20 16:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_oBkE2-PrVmtswqmQP:b-evn7h1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Yes. I mean `DirectLiquidLegionsSketchParams`is always expected to be either `ReachOnlyLiquidLegionsSketchParams` and `LiquidLegionsSketchParams`. In fact,  `DirectReachOnlyLiquidLegionsSketchParams`always = `ReachOnlyLiquidLegionsSketchParams`, `DirectReachAndFrequencyLiquidLegionsSketchParams`always = `LiquidLegionsSketchParams`.
</blockquote></details>

@kungfucraig @SanjayVas  wdyt? Should we remove `DirectLiquidLegionsV2` and use `LiquidLegionsV2` and `ReachOnlyLiquidLegionsV2` then? That is `LiquidLegionsV2` and `ReachOnlyLiquidLegionsV2` are used in both direct and MPC. 


<!-- Sent from Reviewable.io -->

2023-07-20 16:57 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @jiayu-google and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_oDuRcDmJ7oRaZmVXf:b-la5l35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@kungfucraig @SanjayVas  wdyt? Should we remove `DirectLiquidLegionsV2` and use `LiquidLegionsV2` and `ReachOnlyLiquidLegionsV2` then? That is `LiquidLegionsV2` and `ReachOnlyLiquidLegionsV2` are used in both direct and MPC. 
</blockquote></details>

I don't see the need to have both direct and non-direct versions of the same messages. Keep in mind that if we do need these to diverge in the future, doing so to add a new optional field is a binary-compatible change.


<!-- Sent from Reviewable.io -->

2023-07-20 19:05 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_kJeNR2AFIMU5fnoin:-N_ocNMEA__z0a84mYk8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c7fd749d0855d245b22e3d7694dd958d66b4a49a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see the need to have both direct and non-direct versions of the same messages. Keep in mind that if we do need these to diverge in the future, doing so to add a new optional field is a binary-compatible change.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-20 20:30 UTC, kungfucraig requested changes
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 3 of 5 files reviewed, 11 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyD0LBiciW7Ose1OJ:-N_oyD0LBiciW7Ose1OK:b-z8iffz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L50)):*
> ```proto
>   ReachOnlyLiquidLegionsSketchParams sketch_params = 1
>       [(google.api.field_behavior) = REQUIRED];
> }
> ```

nit: end the file with a newline
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 131 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyVuy0DxhIPa9XVdi:-N_oyVuy0DxhIPa9XVdj:bb9jwnl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L131)):*
> ```proto
>       int64 value = 1;
> 
>       // The mechanism used to generate noise during computation.
> ```

We should note that this field need not be populated if no noise was added. This will be the case for the Origin TV data provider.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 183 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyoOcCjNLXJVqlrcq:-N_oyoOcCjNLXJVqlrcr:b4vn86n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L183)):*
> ```proto
>       oneof methodology {
>         // Deterministic count distinct methodology.
>         DeterministicCountDistinct deterministic_count_distinct = 3;
> ```

This is really just "DeterministicCount" there's no notion of distinct here really.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 200 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyvHWBKaVkHjqtGke:-N_oyvHWBKaVkHjqtGkf:bfmwuic) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L200)):*
> ```proto
>       oneof methodology {
>         // Deterministic count distinct methodology.
>         DeterministicCountDistinct deterministic_count_distinct = 3;
> ```

This should be "DeterministicSum"
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 99 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_ozPMg5UJ1l_D8DpVT:-N_ozPMg5UJ1l_D8DpVU:bbwplvg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L99)):*
> ```proto
>   // The recommended computation options to data provider. Data provider may
>   // choose different computation methodology.
>   message Direct {
> ```

We talked about a leaving a TODO for a proto annotation, but given that the Result proto makes it very clear what methods apply to which metrics the annotation seems unnecessary at this point.

@SanjayVas WDYT?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 108 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_ozAxLDPNrIN4eYbOL:-N_ozAxLDPNrIN4eYbOM:b-8cjiqy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L108)):*
> ```proto
>     // Can be used in reach, frequency, impression, or watch duration
>     // computations.
>     DeterministicCountDistinct deterministic_count_distinct = 2;
> ```

The comment will need to be updated when the changes I suggested above are incorporated.

And we'll need to add DeterministicCount and DeterministicSum here.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/sketch_params.proto` line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_ozlI0BhW58fFLWgCQ:-N_ozlI0BhW58fFLWgCR:by6fkfu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/sketch_params.proto#L44)):*
> ```proto
>   // The maximum size of the Liquid Legions sketch.
>   int64 max_size = 2 [(google.api.field_behavior) = REQUIRED];
> }
> ```

nit: newline


<!-- Sent from Reviewable.io -->

2023-07-20 20:43 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 1 of 5 files reviewed, 9 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 131 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyVuy0DxhIPa9XVdi:-N_p-eKx-QIp3fHhuLoL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L131)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We should note that this field need not be populated if no noise was added. This will be the case for the Origin TV data provider.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 183 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyoOcCjNLXJVqlrcq:-N_p0BGb8-XNjrKDgD6N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L183)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is really just "DeterministicCount" there's no notion of distinct here really.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 200 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyvHWBKaVkHjqtGke:-N_p0nt03KtPOpD4KYXz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L200)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This should be "DeterministicSum"
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 108 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_ozAxLDPNrIN4eYbOL:-N_p0siyA3NsQOxET4H1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L108)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The comment will need to be updated when the changes I suggested above are incorporated.

And we'll need to add DeterministicCount and DeterministicSum here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-20 23:47 UTC, SanjayVas reviewed
> Reviewed 1 of 5 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 8 unresolved discussions (waiting on @jiayu-google and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 131 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyVuy0DxhIPa9XVdi:-N_pg6dK9AD-9WgQtUt3:b-vie08m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L131)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This comment is no longer correct w.r.t. the decision to add a NONE value. Instead the field must be populated with NONE if no noise was added.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 99 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_ozPMg5UJ1l_D8DpVT:-N_pgZP48ewHbrZ2lCGa:bk7csap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L99)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We talked about a leaving a TODO for a proto annotation, but given that the Result proto makes it very clear what methods apply to which metrics the annotation seems unnecessary at this point.

@SanjayVas WDYT?
</blockquote></details>

Yeah, I think it's pretty clear what EDPs need to support.


<!-- Sent from Reviewable.io -->

2023-07-21 00:19 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 131 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_oyVuy0DxhIPa9XVdi:-N_pnchi6MWQ5xGCuQbj:bfhz2u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9a6836e548bd12c63856bdb09a98e86340e527ff/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comment is no longer correct w.r.t. the decision to add a NONE value. Instead the field must be populated with NONE if no noise was added.
</blockquote></details>

Thanks for catching it. Done.


<!-- Sent from Reviewable.io -->

2023-07-21 16:56 UTC, kungfucraig requested changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tMthQ06U980yE3Px5:b-d0z0ii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
> ```proto
>       oneof methodology {
>         // Deterministic count methodology.
>         DeterministicCount deterministic_count = 3;
> ```

I think for reach you should still say "DerterministicCountDistinct."
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMMqX0B1-uTSHy6ib:-N_tMMqX0B1-uTSHy6ic:bq0dnvo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L65)):*
> ```proto
>     NOISE_MECHANISM_UNSPECIFIED = 0;
>     // No noise is added.
>     NONE = 1;
> ```

Please do not renumber the enum fields. Set NONE equal to 3. This can cause a lot of problems for running systems and at this point we should assume that there are durable persistent uses of this proto that we do not know about.


<!-- Sent from Reviewable.io -->

2023-07-21 17:04 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tOucm5ipkTrAzYbgO:b-py83zc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think for reach you should still say "DerterministicCountDistinct."
</blockquote></details>

Are they two different things? Should I have both `DerterministicCountDistinct` and `DerterministicCount` in the `direct_computation`? 


<!-- Sent from Reviewable.io -->

2023-07-21 17:11 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tQYtBDUEuE_Hr4YgE:b-1wqh6f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Are they two different things? Should I have both `DerterministicCountDistinct` and `DerterministicCount` in the `direct_computation`? 
</blockquote></details>

From a point of view of a SQL implementation for one you'd write:

select count(VID) from TABLE

and the other

select count(distinct VID) from TABLE;

They are distinct as it were. ;)


<!-- Sent from Reviewable.io -->

2023-07-21 17:12 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tQy5K3XLFRsLK5LM_:b6lwd59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

From a point of view of a SQL implementation for one you'd write:

select count(VID) from TABLE

and the other

select count(distinct VID) from TABLE;

They are distinct as it were. ;)
</blockquote></details>

In fact the first of these is impression count, the second is reach.


<!-- Sent from Reviewable.io -->

2023-07-21 17:15 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tR76nCw5J-4CWlJC1:b-8qv04s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

In fact the first of these is impression count, the second is reach.
</blockquote></details>

To me that sounds like two different operations and so we should have two different methodologies for them. Is that correct?


<!-- Sent from Reviewable.io -->

2023-07-21 17:18 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tSPJO-gkBvQf7Zdv8:bvsit1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

To me that sounds like two different operations and so we should have two different methodologies for them. Is that correct?
</blockquote></details>

yes, the first is DeterministicCount and the second i DeterministicCountDistinct.


<!-- Sent from Reviewable.io -->

2023-07-21 17:28 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tUDU1EefJR_VsjNk_:b-wezuah) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

yes, the first is DeterministicCount and the second i DeterministicCountDistinct.
</blockquote></details>

Thanks for confirming. How about frequency? IIUC, frequency is using DeterministicCountDistinct instead of DeterministicCount, right?


<!-- Sent from Reviewable.io -->

2023-07-21 17:32 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_tVeaG4uWiY2v6Kb9z:b2nign6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for confirming. How about frequency? IIUC, frequency is using DeterministicCountDistinct instead of DeterministicCount, right?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-07-21 18:10 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-N_td1Ui883W3vDyDsFk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMMqX0B1-uTSHy6ib:-N_tcz0rEe6jBTfb8o1z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L65)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please do not renumber the enum fields. Set NONE equal to 3. This can cause a lot of problems for running systems and at this point we should assume that there are durable persistent uses of this proto that we do not know about.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-21 18:12 UTC, SanjayVas reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMMqX0B1-uTSHy6ib:-N_tdSqZ34G4uBTyi6Q2:b-bk6n4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L65)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: You can still put them in the same order with NONE above GEOMETRIC. The declared order need not match the numbering, and should still have its own organization.


<!-- Sent from Reviewable.io -->

2023-07-21 19:42 UTC, kungfucraig approved these changes
> Reviewed 1 of 4 files at r6, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-07-21 19:42 UTC, kungfucraig approved these changes
> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-07-21 20:29 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMMqX0B1-uTSHy6ib:-N_tP79tAV-PU6MFGGnx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: You can still put them in the same order with NONE above GEOMETRIC. The declared order need not match the numbering, and should still have its own organization.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-21 20:35 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-07-21 21:12 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-07-24 16:22 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na7gLhDDo04pcm6Wr9f:b-tr7w9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@kungfucraig 
sorry for the late response. fwiw, `select count(VID) from TABLE` is not the right impression query, since we need to cap the frequency. The right query is
```
with vid_histogram as (
  select vid, count(*) as frequency
  from TABLE
  group by vid
)
select sum(CASE WHEN frequency < cap THEN frequency ELSE cap END 
from vid_histogram 
```
As such, `DerterministicCount` is not a very meaningful name to me.


<!-- Sent from Reviewable.io -->

2023-07-24 17:42 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na7zN30Dmix7nUL1KP0:b9n7vjk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

@kungfucraig 
sorry for the late response. fwiw, `select count(VID) from TABLE` is not the right impression query, since we need to cap the frequency. The right query is
```
with vid_histogram as (
  select vid, count(*) as frequency
  from TABLE
  group by vid
)
select sum(CASE WHEN frequency < cap THEN frequency ELSE cap END 
from vid_histogram 
```
As such, `DerterministicCount` is not a very meaningful name to me.

</blockquote></details>

This comment is attached to the reach query and EDPs don't cap frequency for reach. 

I think we went with just DeterministicCount for impressions. I'd say the capping is a special case here and since it's part of the measurement request is accounted for.

However, to be complete maybe we should add "CappedDeterministicCount?"

@riemanli wdyt? 


<!-- Sent from Reviewable.io -->

2023-07-24 18:07 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na82I4h9MupJgdV2h2N:b-gttbdi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This comment is attached to the reach query and EDPs don't cap frequency for reach. 

I think we went with just DeterministicCount for impressions. I'd say the capping is a special case here and since it's part of the measurement request is accounted for.

However, to be complete maybe we should add "CappedDeterministicCount?"

@riemanli wdyt? 
</blockquote></details>

Do we need to make capping explicitly in the name? If so, `CappedDeterministicCount` for impression sounds good to me.

In a word, if we want to make capping explicitly in the name, here are the `DeterministicCount`s for different measurement types:
* Reach: `DeterministicCountDistinct`
* Frequency: `CappedDeterministicCountDistinct`
* Impression: `CappedDeterministicCount`
* Watch duration: `CappedDeterministicSum`

Please let me know if that's what you think @jiayu-google


<!-- Sent from Reviewable.io -->

2023-07-24 18:15 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na85bWS6zOcuXDkA3DH:b87kruu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Do we need to make capping explicitly in the name? If so, `CappedDeterministicCount` for impression sounds good to me.

In a word, if we want to make capping explicitly in the name, here are the `DeterministicCount`s for different measurement types:
* Reach: `DeterministicCountDistinct`
* Frequency: `CappedDeterministicCountDistinct`
* Impression: `CappedDeterministicCount`
* Watch duration: `CappedDeterministicSum`

Please let me know if that's what you think @jiayu-google
</blockquote></details>

FWIW I don't think we need the `Capped` distinction as everything in the MeasurementSpec needs to be followed regardless of the methodology. Put another way, the MeasurementSpec constrains the implementation of the methodology.


<!-- Sent from Reviewable.io -->

2023-07-24 18:17 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na85Loq9WrUDtvEAKde:b-ehd0k2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FWIW I don't think we need the `Capped` distinction as everything in the MeasurementSpec needs to be followed regardless of the methodology. Put another way, the MeasurementSpec constrains the implementation of the methodology.
</blockquote></details>

From the methology perspective, I would call them as
- Reach: option 1 = `DeterministicCountDistinct`, 2 = `LiquidLegionsCountDistinct`
- Frequency:  option 1 =`DeterministicHistogram`, 2 =`LiquidLegionsHistogram`
- Impression: option 1 =`FixedCapDeterministicCount`, 2 =`AdaptiveCapDeterministicCount`
- Duration: option 1 = `FixedCapDeterministicSum`, 2 =`AdaptiveCapDeterministicSum`

+1 to Sanjay. We dont need the `cap` distinction. It's just a clarification and can be removed. But we later need the `FixedCap` vs `AdaptiveCap` distinction.


<!-- Sent from Reviewable.io -->

2023-07-24 18:25 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na87SgGC8JuPGKJVy2V:bt8l6mz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

From the methology perspective, I would call them as
- Reach: option 1 = `DeterministicCountDistinct`, 2 = `LiquidLegionsCountDistinct`
- Frequency:  option 1 =`DeterministicHistogram`, 2 =`LiquidLegionsHistogram`
- Impression: option 1 =`FixedCapDeterministicCount`, 2 =`AdaptiveCapDeterministicCount`
- Duration: option 1 = `FixedCapDeterministicSum`, 2 =`AdaptiveCapDeterministicSum`

+1 to Sanjay. We dont need the `cap` distinction. It's just a clarification and can be removed. But we later need the `FixedCap` vs `AdaptiveCap` distinction.
</blockquote></details>

How would adaptive cap interact with the maximum frequency specified in the measurement spec? Do we adapt to some cap that's <= the specified max?


<!-- Sent from Reviewable.io -->

2023-07-24 18:27 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na88TWK-ouC9Z8Nu41w:b-ejt3lw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How would adaptive cap interact with the maximum frequency specified in the measurement spec? Do we adapt to some cap that's <= the specified max?
</blockquote></details>

I prefer making Impression.max_frequency_per_user optional in the future. If it is specified, then respect it. Otherwise, EDP chooses it.

If we don't make this field optional, then what you suggested sounds quite reasonable.


<!-- Sent from Reviewable.io -->

2023-07-24 18:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na8DsTbBtjpaTWt-WC8:b70wul0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
> I prefer making Impression.max\_frequency\_per\_user optional in the future. If it is specified, then respect it. Otherwise, EDP chooses it.

If I understand correctly, what you mean is if the measurement consumer sets `impression.max_frequency_per_user`, then the EDP will use `FixedCapDeterministicCount`; otherwise the EDP will use `AdaptiveCapDeterministicCount`. Is that correct?

If so, I am sure if this is a correct way to do. @SanjayVas please correct me if I am wrong, but I think how an EDP chooses a methodology shouldn't be affected by the MC.


<!-- Sent from Reviewable.io -->

2023-07-24 19:03 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na8GooP5JdnS-kaN8k5:ba9u12p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> I prefer making Impression.max\_frequency\_per\_user optional in the future. If it is specified, then respect it. Otherwise, EDP chooses it.

If I understand correctly, what you mean is if the measurement consumer sets `impression.max_frequency_per_user`, then the EDP will use `FixedCapDeterministicCount`; otherwise the EDP will use `AdaptiveCapDeterministicCount`. Is that correct?

If so, I am sure if this is a correct way to do. @SanjayVas please correct me if I am wrong, but I think how an EDP chooses a methodology shouldn't be affected by the MC.
</blockquote></details>

I don't think we need the "FixedCap" in front of the impression and duration. Otherwise the above looks good, but let's not add the adaptive stuff just yet (not until we're ready to implement it).


<!-- Sent from Reviewable.io -->

2023-07-24 19:58 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na8AJn2Ag21nYxkwNgP:bum8xzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think we need the "FixedCap" in front of the impression and duration. Otherwise the above looks good, but let's not add the adaptive stuff just yet (not until we're ready to implement it).
</blockquote></details>

It's more that if the MC does not set `maximum_frequency` (`max_frequency_per_user` is [going away](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/issues/159) and will [be replaced](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/issues/160) by `maximum_frequency`), then the EDP is not constrained by that in its choice of methodology.


<!-- Sent from Reviewable.io -->

2023-07-24 20:05 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-Na8VMq4268emvThQjnB:b-8ykn9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Thanks Sanjay, +1
Craig, sgtm to remove FixedCap.

Rieman, fwiw, LiquidLegionsCount (of impressions) is a thing. If Meta is using LiquidLegionsCountDistinct and LiquidLegionsHistogram, there's chance they are also using LiquidLegionsCount. Worth checking with them at some time
</blockquote></details>

If they are doing capping, yeah. That would be a way to do it. Thanks for flagging this.


<!-- Sent from Reviewable.io -->

2023-07-26 20:01 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 38 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIe3E1C9FSJ16-YNjT:-NaIjXtB-DhyRTzyO6vs:bau9co0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this isn't configuration (which implies its part of ProtocolConfig), but rather the parameters used when applying the methodology.
</blockquote></details>

Fixed this one and the other methodologies.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 51 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIczMz5MROAqOvrtIc:-NaIjoV31E_YPobMdz_w:b-kpet8c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think the EDP can choose the max frequency.
</blockquote></details>

Thanks for pointing it out. Removed. This also reminds me max frequency should be in the direct histogram options of the protocol config.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 133 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIevl13axG8s2gI2ph:-NaIkG5qDvhbwoABS0zB:bad59sg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: make it clear that this should be set
</blockquote></details>

Thanks for the suggestion. Done
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 135 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIcHHt3vSjUOa9mEc9:-NaImSe-5O_sxWSSn_R4:b-stnn5d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L135)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought that this was fixed in api-linter v1.50.0 (see https://github.com/googleapis/api-linter/commit/16770d58a9251c7aa793304f7e129639d4da1368). This repo is using v1.52.0.
</blockquote></details>

Thanks for pointing it out! The PR was based on an older main. Maybe that's why I got the error from the CI checks. It's removed now.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 95 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIdMD9DxDe_aPKL17x:-NaIlHaMEjkzkICxGhBm:bnpqtco) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: these are parameters for a given methodology
</blockquote></details>

Fixed this and other messages.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 107 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIgUho8qO7XpjgAdSS:-NaIl42y1Fy6rg-4Lsoz:b-kih9l6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remove this. This first part of this comment is already indicated on the field. The second part is incorrect, and the correct version is already on the `direct` field in the `Protocol` message.
</blockquote></details>

Got it. Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 115 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaIg-PsExYMuHIDT8jA:-NaIlC573GmN5B-57c23:bd0jggz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/762fc619379cbce3eca101d3b5f6a125bde1bb38/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is implying the DataProvider may use something other than one of the options specified here.
</blockquote></details>

Thanks for catching that. Done.


<!-- Sent from Reviewable.io -->

2023-07-26 20:22 UTC, kungfucraig approved these changes
> Reviewed 2 of 4 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-07-26 20:52 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-07-27 15:20 UTC, stevenwarejones requested changes
> Reviewed 1 of 4 files at r6, 1 of 4 files at r11, 1 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google and @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 30 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMsCEXEG4J07o2h-Nq:-NaMsCEXEG4J07o2h-Nr:b-c80el9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L30)):*
> ```proto
> 
> // Parameters used when applying the deterministic histogram methodology.
> message DeterministicHistogram {}
> ```

also, do we really need all these different deterministic types? Why not just a single 
```
message Deterministic {}
```
What kind of params would we want in the future to justify distinct message types?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-NaMh27S6Gm3gpimF6nC:b-vsmvqz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@stevenwarejones Can you confirm?
</blockquote></details>

Yeah - we are using a count on the Liquid Legions sketch. Also, what about LiquidLegionsSum?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvycUBZRQjSB9JZP9:-NaMvycUBZRQjSB9JZPA:bzfo0ep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L136)):*
> ```proto
>       // `GEOMETRIC`.
>       // (-- TODO: set required once EDPs incorporate the new API changes. --)
>       ProtocolConfig.NoiseMechanism noise_mechanism = 2;
> ```

seems kind of odd to import ProtocolConfig here. See my other suggestion about moving this enum about of ProtocolConfig
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvLVMB0J_TS--JvtN:-NaMvLVMB0J_TS--JvtO:b-k8fdaj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L139)):*
> ```proto
> 
>       // The computation methodology done by data provider.
>       oneof methodology {
> ```

Can you also add these to MeasurementSpec so the MC can give best practice/preferred sketch params?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 60 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMubHD-FKrPr7GRNYW:-NaMubHD-FKrPr7GRNYX:b-kn499m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L60)):*
> ```proto
> 
>   // The mechanism used to generate noise in computations.
>   enum NoiseMechanism {
> ```

wdyt about moving this to its own message type NoiseParams or something?


<!-- Sent from Reviewable.io -->

2023-07-27 17:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 30 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMsCEXEG4J07o2h-Nq:-NaNGvxAEzGweuMgHnce:b-n82txm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

also, do we really need all these different deterministic types? Why not just a single 
```
message Deterministic {}
```
What kind of params would we want in the future to justify distinct message types?
</blockquote></details>

My understanding is that we want to be specific and explicit about how a computation is done. 
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-NaNJ2PW9_8rrPSqSGNa:bohbls0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Yeah - we are using a count on the Liquid Legions sketch. Also, what about LiquidLegionsSum?
</blockquote></details>

Sure we can add those two. Any values apart from sketch size and decay rate that the EDP will choose and should be outputted to result?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvLVMB0J_TS--JvtN:-NaNHNNX3uvRZmNeNfSM:b2rb7jy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L139)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Can you also add these to MeasurementSpec so the MC can give best practice/preferred sketch params?
</blockquote></details>

I am not sure if MC is the right entity to make that suggestion. @kungfucraig @SanjayVas wdyt?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 60 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMubHD-FKrPr7GRNYW:-NaNGVU_8nnZPKjbplEW:b86jp8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about moving this to its own message type NoiseParams or something?
</blockquote></details>

Could we hold on that for now? Renjie is working on reach-only implementation, and change like this will cause a lot of problems to his work. 
cc @kungfucraig 


<!-- Sent from Reviewable.io -->

2023-07-27 18:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvycUBZRQjSB9JZP9:-NaNbiU780tySTk8fiIo:bgvwtk1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L136)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

seems kind of odd to import ProtocolConfig here. See my other suggestion about moving this enum about of ProtocolConfig
</blockquote></details>

Thanks for brining it up. Please see my response in the other comment.


<!-- Sent from Reviewable.io -->

2023-07-27 18:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 60 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMubHD-FKrPr7GRNYW:-NaNbsQL1ZA29jK7o2kt:bbs5r8p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L60)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Could we hold on that for now? Renjie is working on reach-only implementation, and change like this will cause a lot of problems to his work. 
cc @kungfucraig 
</blockquote></details>

I can add a TODO to indicate that if that works.


<!-- Sent from Reviewable.io -->

2023-07-27 20:00 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaNugbW4bl9GTpJV7D4:-NaNugbW4bl9GTpJV7D5:b-rmz2xg) (no related file):*
I think the PR description is a bit confusing as well as being out-of-date.

What this PR is really doing is capturing information about methodologies that are currently in use so that the Measurement contains all the information needed to compute result variance. The parameters that the Kingdom chooses (e.g. available methodologies) go in the ProtocolConfig. The parameters that the result provider chooses (e.g. which methodology of those available) go in the Measurement result.

___
___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 30 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMsCEXEG4J07o2h-Nq:-NaNqvGA-56_3_A-apg0:b-jegceu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L30)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

My understanding is that we want to be specific and explicit about how a computation is done. 
</blockquote></details>

I believe it's just to be consistent so that each methodology has its own message.

The fact that these are deterministic is also not the most salient point of what is in common amongst these methodologies.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-NaNuEL5-VzJyukmlut2:b-gf1bm0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
> Also, what about LiquidLegionsSum?

What is that? Is it something that is already or imminently being used?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvycUBZRQjSB9JZP9:-NaNtiPm4JIJMUTh3Zzl:bwm9fhx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L136)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for brining it up. Please see my response in the other comment.
</blockquote></details>

I agree, though maybe not in this PR to avoid churn. Perhaps add a TODO?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvLVMB0J_TS--JvtN:-NaNtqLs4Mpy9H-ydk7e:b-vr9q49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L139)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I am not sure if MC is the right entity to make that suggestion. @kungfucraig @SanjayVas wdyt?
</blockquote></details>

We'd have to discuss that separately if we want to add that feature. This PR is just trying to capture the current methodologies that are already in use so that there is enough information to compute result variance.


<!-- Sent from Reviewable.io -->

2023-07-27 20:18 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvLVMB0J_TS--JvtN:-NaNzNls3nmqe09fSgcv:bo4srz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We'd have to discuss that separately if we want to add that feature. This PR is just trying to capture the current methodologies that are already in use so that there is enough information to compute result variance.
</blockquote></details>

I don't think the MC should specify these either. Best to leave it as config in the Kingdom or to let the EDP decide. I'd support adding a TODO to add a recommended set of sketching parameters, but if we can keep it out of this pass it will help speed error bars along.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 60 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMubHD-FKrPr7GRNYW:-NaNzvFvDegKpKrTGY2f:bsay9if) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L60)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I can add a TODO to indicate that if that works.
</blockquote></details>

I'd like to keep this here for now so that we can get Error Bars done. This is already a lot of scope creep as it is.


<!-- Sent from Reviewable.io -->

2023-07-27 22:26 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-NaOSF3O8VaHTMxTGi_H:b-9fdj90) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Also, what about LiquidLegionsSum?

What is that? Is it something that is already or imminently being used?
</blockquote></details>

essentially, a sum of watch duration, instead of impression counts, based on a liquid legions sketch
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvycUBZRQjSB9JZP9:-NaOS7x94hCSrlkPrYQV:b-rq4zvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I agree, though maybe not in this PR to avoid churn. Perhaps add a TODO?
</blockquote></details>

i'm okay with a TODO
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvLVMB0J_TS--JvtN:-NaORIvPCmkD7MjNwIQC:b-padjq9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L139)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think the MC should specify these either. Best to leave it as config in the Kingdom or to let the EDP decide. I'd support adding a TODO to add a recommended set of sketching parameters, but if we can keep it out of this pass it will help speed error bars along.
</blockquote></details>

I'm fine with a TODO.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 60 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMubHD-FKrPr7GRNYW:-NaOS-311xmSDyKmFUYB:b-lb4fr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L60)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'd like to keep this here for now so that we can get Error Bars done. This is already a lot of scope creep as it is.
</blockquote></details>

add a TODO


<!-- Sent from Reviewable.io -->

2023-07-28 00:37 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaNugbW4bl9GTpJV7D4:-NaOQhfg0pXJzw7e1cTD:b-orcjpg) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the PR description is a bit confusing as well as being out-of-date.

What this PR is really doing is capturing information about methodologies that are currently in use so that the Measurement contains all the information needed to compute result variance. The parameters that the Kingdom chooses (e.g. available methodologies) go in the ProtocolConfig. The parameters that the result provider chooses (e.g. which methodology of those available) go in the Measurement result.
</blockquote></details>

Thanks for catching that. Updated.

___
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 137 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-N_tMthQ06U980yE3Px4:-NaOvC3P89LMEWePee0O:b-6rbf4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7ccc9e17d971286e71dacc0304f404f542edf137/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L137)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

essentially, a sum of watch duration, instead of impression counts, based on a liquid legions sketch
</blockquote></details>

Added. Please take a look.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvycUBZRQjSB9JZP9:-NaOT4yq-kH_7EMidHDL:bi1gnrc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L136)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm okay with a TODO
</blockquote></details>

I added a TODO in `protocol_config.proto` where the noise mechanism message is currently defined.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMvLVMB0J_TS--JvtN:-NaOTVVC8HDTR2TH8vni:b-8rrizx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L139)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm fine with a TODO.
</blockquote></details>

Added a TODO for adding recommended parameter values under `Direct` in `protocol_config.proto`
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 60 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaMubHD-FKrPr7GRNYW:-NaOYgUe2RXNTQ_E7lfq:bqmjwcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/a31750b21dba130dbd878bb00426811a3665d415/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add a TODO
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2023-07-28 00:39 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 54 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaOvocF7bczYJlVoPnC:-NaOvocF7bczYJlVoPnD:bu3rsav) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/3f6a6e176133d96ef28bf1765e75daf949ac9376/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L54)):*
> ```proto
> // methodology.
> //
> // To obtain differentially private result, one should add a DP noise to the
> ```

@jiayu-google please take a look if there is any other detail you would like to add.


<!-- Sent from Reviewable.io -->

2023-07-28 15:33 UTC, stevenwarejones reviewed
> Reviewed 3 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 147 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaS740Z1Oz7b0leWRpZ:-NaS740Z1Oz7b0leWRp_:b-tmnj3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L147)):*
> ```proto
>         LiquidLegionsCountDistinct liquid_legions_count_distinct = 4;
> 
>         // Liquid Legions histogram methodology.
> ```

just to clarify.... this is for using the LiquidLegionsHistogram method for measuring reach?


<!-- Sent from Reviewable.io -->

2023-07-28 16:14 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 147 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaS740Z1Oz7b0leWRpZ:-NaSFnKY8bZiA_mKsVIT:bsyah6t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L147)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just to clarify.... this is for using the LiquidLegionsHistogram method for measuring reach?
</blockquote></details>

Yes it may be used when the reach is computed as part of REACH_AND_FREQUENCY


<!-- Sent from Reviewable.io -->

2023-07-28 17:21 UTC, SanjayVas approved these changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-28 19:37 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 167 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaSzcGM7Ys_Agm1-W7W:-NaSzcGM7Ys_Agm1-W7X:b-o5cb0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L167)):*
> ```proto
>     //
>     // Can be used in reach computations.
>     DirectReachOnlyLiquidLegionsV2 direct_reach_only_liquid_legions_v2 = 7;
> ```

Can you add a TODO to add DirectReachOnlyHLL++ ?


<!-- Sent from Reviewable.io -->

2023-07-28 19:39 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 167 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaSzcGM7Ys_Agm1-W7W:-NaT-pUpBaLZz16e4lH0:b-r7uspn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L167)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Can you add a TODO to add DirectReachOnlyHLL++ ?
</blockquote></details>

I don't think we need this TODO until/unless we decide to support it. (TODO implies we definitely want to support it in the future)


<!-- Sent from Reviewable.io -->

2023-07-28 21:10 UTC, kungfucraig approved these changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 167 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaSzcGM7Ys_Agm1-W7W:-NaTKSwJBIK3_iJAy87L:bwodiyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L167)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we need this TODO until/unless we decide to support it. (TODO implies we definitely want to support it in the future)
</blockquote></details>

A GitHub issue instead?


<!-- Sent from Reviewable.io -->

2023-07-28 21:15 UTC, kungfucraig approved these changes
Can you update your TODOs to use the format documented here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-:-NaTLXamD58ycog4oOib:b-jpnhje)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-28 21:16 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 167 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaSzcGM7Ys_Agm1-W7W:-NaTLmwnDow929g-2qVW:boh46ud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L167)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

A GitHub issue instead?
</blockquote></details>

It could be a feature request, but wouldn't bother filing it until we know someone actually wants it.


<!-- Sent from Reviewable.io -->

2023-07-28 21:37 UTC, riemanli reviewed
Thanks for pointing it out and sharing the correct format. Done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-:-NaTOYovBQ_W0nc0BDJX:b8oyrkf)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-31 13:20 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 167 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaSzcGM7Ys_Agm1-W7W:-Nag5TGLDVHrLPgKslUt:b-tfy75x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L167)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It could be a feature request, but wouldn't bother filing it until we know someone actually wants it.
</blockquote></details>

what's the lift on the api side? Its something we have on our task list


<!-- Sent from Reviewable.io -->

2023-07-31 19:05 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 167 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaSzcGM7Ys_Agm1-W7W:-NahK35nEkNb-H1VMUgW:b-9yx0yb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/bff6508b5d912d80feee5e78d741360ee5607401/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L167)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what's the lift on the api side? Its something we have on our task list
</blockquote></details>

Relatively minor once we have variance (error bars) implemented.

The intent of this PR is just to capture the initial (i.e. "current") methodologies, knowing that we expect to add more.


<!-- Sent from Reviewable.io -->

2023-07-31 21:00 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 4 unresolved discussions (waiting on @jiayu-google and @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-07-31 21:06 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-:-NahlR8t-BqM_8XLVCzd:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-07-31 21:27 UTC, kungfucraig approved these changes
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-01 14:51 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 4 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-03 17:04 UTC, jiayu-google requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 149 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawKiJkDZ_SEhctpSR5:-NawKiJkDZ_SEhctpSR6:b3rmyvc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L149)):*
> ```proto
> 
>         // Liquid Legions histogram methodology.
>         LiquidLegionsHistogram liquid_legions_histogram = 5;
> ```

`LiquidLegionsHistogram` is not a methodology for Reach. 

IMO the methodology refers to the effective methodology, instead of the detailed algorithm. When you use a `LiquidLegionsHistogram` to compute reach, the result is the same as `LiquidLegionCountDistinct`. So you should simply say I use the `LiquidLegionsCountDistinct` methodology for reach.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 175 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawLfQVB_b0KYC9yPYc:-NawLfQVB_b0KYC9yPYd:b-3l1638) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L175)):*
> ```proto
>       oneof methodology {
>         // Deterministic histogram methodology.
>         DeterministicHistogram deterministic_histogram = 3;
> ```

Shall we rename `Histogram` as `Distribution`?

The frequency result is called `relative_frequency_distribution`. The term "distribution" indicates that we are computing a relative histogram.


<!-- Sent from Reviewable.io -->

2023-08-03 18:14 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 175 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawLfQVB_b0KYC9yPYc:-NawawY08zZBVEXxtDlS:b-t2ea93) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L175)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Shall we rename `Histogram` as `Distribution`?

The frequency result is called `relative_frequency_distribution`. The term "distribution" indicates that we are computing a relative histogram.
</blockquote></details>

Let's not.


<!-- Sent from Reviewable.io -->

2023-08-03 18:30 UTC, jiayu-google requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 175 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawLfQVB_b0KYC9yPYc:-NaweR-40GMRYy2EqTLP:bqnbj5d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L175)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Let's not.
</blockquote></details>

how about adding a comment that `histogram` refers to relative histogram?


<!-- Sent from Reviewable.io -->

2023-08-03 18:57 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 149 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawKiJkDZ_SEhctpSR5:-NawhQyy3Y_iWfx-yqiW:brv2nmg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L149)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

`LiquidLegionsHistogram` is not a methodology for Reach. 

IMO the methodology refers to the effective methodology, instead of the detailed algorithm. When you use a `LiquidLegionsHistogram` to compute reach, the result is the same as `LiquidLegionCountDistinct`. So you should simply say I use the `LiquidLegionsCountDistinct` methodology for reach.
</blockquote></details>

Sounds good
@stevenwarejones  sorry I was wrong when you asked about `LiquidLegionsHistogram` in the reach result.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 175 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawLfQVB_b0KYC9yPYc:-Nawhx3nCBCeLlLddYvo:boystop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L175)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

how about adding a comment that `histogram` refers to relative histogram?
</blockquote></details>

Based on offline discussion, we will rename `*Histogram` to `*Distribution`


<!-- Sent from Reviewable.io -->

2023-08-03 19:04 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-08-03 19:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 149 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawKiJkDZ_SEhctpSR5:-Nawo-ql5EYDG2pfC-yb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L149)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Sounds good
@stevenwarejones  sorry I was wrong when you asked about `LiquidLegionsHistogram` in the reach result.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 175 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NawLfQVB_b0KYC9yPYc:-Nawo4-O7IHElP5GGQT_:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0cfd4d232e2aba8365e325908fad3e52594b90c6/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L175)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Based on offline discussion, we will rename `*Histogram` to `*Distribution`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-03 20:58 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-:-NaxBNBFCs-8Yy55ZXSr:bnfp4nl)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-04 14:57 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-08-04 19:51 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @kungfucraig)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaNugbW4bl9GTpJV7D4:-Nb15TGnAFH2iXntiLhz:bkdqsnf) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for catching that. Updated.
</blockquote></details>

PR description is still "Add DirectComputation for direct measurements", which I don't believe is accurate.

___


<!-- Sent from Reviewable.io -->

2023-08-04 22:22 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @kungfucraig)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaNugbW4bl9GTpJV7D4:-Nb1czO-69P8Xc0lUTm_:b-96jzmh) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

PR description is still "Add DirectComputation for direct measurements", which I don't believe is accurate.
</blockquote></details>

Changed the PR title to "Add direct computation methodologies to protocol config and measurement results"

___


<!-- Sent from Reviewable.io -->

2023-08-04 22:53 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-08-08 15:10 UTC, kungfucraig approved these changes
> Reviewed 2 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-08-09 17:09 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 9 unresolved discussions (waiting on @iverson52000, @jiayu-google, and @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-08-09 17:11 UTC, iverson52000 approved these changes
> Reviewed 1 of 5 files at r14, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-08-09 17:15 UTC, kungfucraig approved these changes
> Reviewed 1 of 3 files at r18, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-08-11 18:26 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-08-17 16:27 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 116 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc3JVt2A03PIovcwQvL:-Nc3JVt2A03PIovcwQvM:b-ngjwnv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8cfe15b89c0a4bfdb6fdbf7b3d226263babeb857/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L116)):*
> ```proto
>     }
>     // Configuration parameters for the deterministic count methodology.
>     message DeterministicCount {}
> ```

@stevenwarejones for the population direct measurement, would it make sense to say it's using `DeterministicCount` methodology? Or should I add a new methodology for it?


<!-- Sent from Reviewable.io -->

2023-08-18 22:25 UTC, stevenwarejones approved these changes
> Reviewed 1 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @iverson52000, @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 116 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc3JVt2A03PIovcwQvL:-Nc9k3bWBcsaQxxfsutY:bixrb5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8cfe15b89c0a4bfdb6fdbf7b3d226263babeb857/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L116)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@stevenwarejones for the population direct measurement, would it make sense to say it's using `DeterministicCount` methodology? Or should I add a new methodology for it?
</blockquote></details>

I think deterministic fits well. You agree @kungfucraig ?


<!-- Sent from Reviewable.io -->

2023-08-18 23:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @iverson52000, @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 230 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc9zMib3MJQUt8-G1Wb:-Nc9zMib3MJQUt8-G1Wc:bl6nlxd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/326a60f0dec0302f9f925db6c6f030e47d7d67b5/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L230)):*
> ```proto
>     message Population {
>       // The population value.
>       int64 value = 1;
> ```

@stevenwarejones in addition to methodology, I wonder if I also need to add a noise mechanism field for population measurement. Are population measurements noised? 


<!-- Sent from Reviewable.io -->

2023-08-19 00:06 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @iverson52000, @kungfucraig, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 54 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaOvocF7bczYJlVoPnC:-NcA5gT0BTsc9OlHsti9:bykuo4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/3f6a6e176133d96ef28bf1765e75daf949ac9376/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L54)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@jiayu-google please take a look if there is any other detail you would like to add.
</blockquote></details>

Sorry I missed this comment before. Looks good to me.
Nit: `sampling_indicator_size` is not used in the error bar calculation. I'm OK if you remove this field from `LiquidLegionsDistribution`.


<!-- Sent from Reviewable.io -->

2023-08-21 00:49 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @iverson52000, @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 230 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc9zMib3MJQUt8-G1Wb:-NcKZGrH9LZEXJskOIAQ:b99zdu7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/326a60f0dec0302f9f925db6c6f030e47d7d67b5/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L230)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@stevenwarejones in addition to methodology, I wonder if I also need to add a noise mechanism field for population measurement. Are population measurements noised?
</blockquote></details>

population measurements should not be noised (at least with the current design)


<!-- Sent from Reviewable.io -->

2023-08-21 16:58 UTC, kungfucraig approved these changes
> Reviewed 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 230 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc9zMib3MJQUt8-G1Wb:-NcO13X9CNbjyIRzfM8s:b-k1d11c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/326a60f0dec0302f9f925db6c6f030e47d7d67b5/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L230)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

population measurements should not be noised (at least with the current design)
</blockquote></details>

+1 the population measurement should not be noised
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 116 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc3JVt2A03PIovcwQvL:-NcO1Cy09UEUVVyAYaAP:bb7ohn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8cfe15b89c0a4bfdb6fdbf7b3d226263babeb857/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L116)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think deterministic fits well. You agree @kungfucraig ?
</blockquote></details>

sgtm


<!-- Sent from Reviewable.io -->

2023-08-21 16:59 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @riemanli, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-21 18:26 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 230 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc9zMib3MJQUt8-G1Wb:-NcO3wGrDsXRY4x_Oqds:b-mm01l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/326a60f0dec0302f9f925db6c6f030e47d7d67b5/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L230)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1 the population measurement should not be noised
</blockquote></details>

Got it thanks for confirming. Giving a second thought about it, I think adding a noise field makes sense because (1) EDP could indicate no noise by using `NOISE_MECHANISM.NONE` and (2) it's consistent with other measurement result type. Wdyt?


<!-- Sent from Reviewable.io -->

2023-08-21 20:36 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @iverson52000, @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 54 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NaOvocF7bczYJlVoPnC:-NcO2x9gAUl1oprbUxlv:b-767rou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/3f6a6e176133d96ef28bf1765e75daf949ac9376/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L54)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Sorry I missed this comment before. Looks good to me.
Nit: `sampling_indicator_size` is not used in the error bar calculation. I'm OK if you remove this field from `LiquidLegionsDistribution`.
</blockquote></details>

Removed `sampling_indicator_size`
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 230 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc9zMib3MJQUt8-G1Wb:-NcOnQ6i7vO3IWTuRy7v:bwcc21r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/326a60f0dec0302f9f925db6c6f030e47d7d67b5/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L230)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If we add it then the PDP implementation will either 1) have to throw an error if it's set; or 2) implement - neither of which is necessary if we just omit it.
</blockquote></details>

Got it. Thanks Craig.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 116 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-Nc3JVt2A03PIovcwQvL:-NcO5czI00tel747e2Rf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8cfe15b89c0a4bfdb6fdbf7b3d226263babeb857/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L116)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 21:06 UTC, kungfucraig approved these changes
> Reviewed 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-22 15:16 UTC, stevenwarejones reviewed
> Reviewed 2 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 64 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcSoJs37CUrn9xe65RW:-NcSoJs37CUrn9xe65RX:bfnusv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cf1af8937a764c491e1c99a79193ac677381c03a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L64)):*
> ```proto
> 
>   // The size of the distribution of the sampling indicator value.
>   int64 sampling_indicator_size = 3 [(google.api.field_behavior) = REQUIRED];
> ```

we don't need this to compute the error bar? I thought we did.


<!-- Sent from Reviewable.io -->

2023-08-22 16:41 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 64 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcSoJs37CUrn9xe65RW:-NcT6QCKDcjxg6Vp3ZN3:bxzgvxd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cf1af8937a764c491e1c99a79193ac677381c03a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L64)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we don't need this to compute the error bar? I thought we did.
</blockquote></details>

Based on what @jiayu-google said in the other thread, we don't need it for error bar calculations.


<!-- Sent from Reviewable.io -->

2023-08-22 21:35 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 64 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcSoJs37CUrn9xe65RW:-NcU9fkK43rireAvmpiX:b-buyxv2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cf1af8937a764c491e1c99a79193ac677381c03a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L64)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Based on what @jiayu-google said in the other thread, we don't need it for error bar calculations.
</blockquote></details>

Yeah i think `sampling_indicator_size` doesn't affect the error bar as long as it's large enough. Whether `sampling_indicator_size` is 10M or 20M doesn't matter.


<!-- Sent from Reviewable.io -->

2023-08-22 23:32 UTC, riemanli commented
* Added new documents about what the default methodology is selected when EDPs haven't fully incorporated the new changes.
* Removed `maximum_frequency` in the direct protocol config as it's not really used in the system. A comprehensive refactoring is in #165 which is going to move all `maximum_frequency` from the protocol config to measurement spec.

2023-08-24 13:53 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r22, 1 of 2 files at r23.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 64 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcSoJs37CUrn9xe65RW:-NcboF_QDTotO-ZF-RJ1:b-kuxw39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cf1af8937a764c491e1c99a79193ac677381c03a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L64)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Yeah i think `sampling_indicator_size` doesn't affect the error bar as long as it's large enough. Whether `sampling_indicator_size` is 10M or 20M doesn't matter.
</blockquote></details>

it sounds like small values might change the error bar then. Are there use cases where this might happen?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 127 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcboXrN1dMxRX3dNrAu:-NcboXrN1dMxRX3dNrAv:b-vuqirc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cc2d72101932b11d9eb64ef6f2e80a04b8c8e0be/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L127)):*
> ```proto
>     message LiquidLegionsDistribution {
>       // The maximum frequency to reveal in the distribution.
>       int32 maximum_frequency = 1;
> ```

why is this removed?


<!-- Sent from Reviewable.io -->

2023-08-24 13:59 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NcbpmZV5JEiZQOoIoE6:b-4zrggo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
> ```proto
> // `Requisition`s using this protocol can be fulfilled by calling
> // RequisitionFulfillment/FulfillRequisition with an encrypted sketch.
> message LiquidLegionsDistribution {
> ```

should vid sampling rate be included as well?


<!-- Sent from Reviewable.io -->

2023-08-24 16:49 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NccR2ak6GWtZJc59-6B:b-d4kowd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should vid sampling rate be included as well?
</blockquote></details>

Do you mean VID sampling interval? It's in measurement spec https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L42-L47
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 127 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcboXrN1dMxRX3dNrAu:-NccPXsxDj7Ien7PybyH:bad26oh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cc2d72101932b11d9eb64ef6f2e80a04b8c8e0be/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L127)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is this removed?
</blockquote></details>

Maximum frequency in protocol config will be moved to measurement spec by #165. Since direct methodologies like this one won't be used any time soon, we think it's ok to reconcile the change of #165 earlier in this PR to avoid unnecessary conflicts. 


<!-- Sent from Reviewable.io -->

2023-08-24 18:20 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NcclUnqBUR98CvVrpA9:b-1etxgx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Do you mean VID sampling interval? It's in measurement spec https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L42-L47
</blockquote></details>

is/should that field be required for direct measurements? or should we allow EDPs to specify their own and then report that back here.


<!-- Sent from Reviewable.io -->

2023-08-24 18:28 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NcclrnDDXq2oKOpK9vQ:b-gkj3tr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is/should that field be required for direct measurements? or should we allow EDPs to specify their own and then report that back here.
</blockquote></details>

My understanding is that the measurement should be computed with the parameters specified by the user in the measurement spec regardless its direct or MPC.


<!-- Sent from Reviewable.io -->

2023-08-24 18:29 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 64 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcSoJs37CUrn9xe65RW:-NccnftB19PqjAvPwiuP:bjpom9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/cf1af8937a764c491e1c99a79193ac677381c03a/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L64)):*
> -   Still remove`sampling_indicator_size` from this `LiquidLegionsDistribution` message.
> -   Add a comment that "When using this LiquidLegionsDistribution methodology, EDPs must use enough number of bits to represent the fingerprints in the LiquidLegions. That is, you should avoid the possibility of representing two VIDs as the same fingerprint."

Does this sound good to you @stevenwarejones?


<!-- Sent from Reviewable.io -->

2023-08-24 22:29 UTC, kungfucraig approved these changes
> Reviewed 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-25 01:04 UTC, stevenwarejones requested changes
> Reviewed 1 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NceCsJZE6k6ExQHEAYz:bbc2tx6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

My understanding is that the measurement should be computed with the parameters specified by the user in the measurement spec regardless its direct or MPC.
</blockquote></details>

is this something we might want to let EDPs decide for direct measurements? @jiayu-google  @kungfucraig 


<!-- Sent from Reviewable.io -->

2023-08-25 14:55 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-Nch5jmT8ZY9I14KS9_2:bs742k4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this something we might want to let EDPs decide for direct measurements? @jiayu-google  @kungfucraig
</blockquote></details>

It's possible we could let EDPs decide, but this is also something we can add if/when the issue comes up.


<!-- Sent from Reviewable.io -->

2023-08-25 15:54 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NchOSgeBk4K2jRKXuDZ:bqqu5jn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's possible we could let EDPs decide, but this is also something we can add if/when the issue comes up.
</blockquote></details>

+1 to Craig.
EDP can control the computational complexity by LiquidLegionsDistribution.max_size, and it's cleaner to respect MeasurementSpec for the sampling interval.


<!-- Sent from Reviewable.io -->

2023-08-28 22:53 UTC, riemanli reviewed
> Dismissed @jiayu-google from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NcyLQhw6OieaigCr35x:b-oxwhv4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

+1 to Craig.
EDP can control the computational complexity by LiquidLegionsDistribution.max_size, and it's cleaner to respect MeasurementSpec for the sampling interval.
</blockquote></details>

Does that work for you @stevenwarejones?


<!-- Sent from Reviewable.io -->

2023-08-30 15:59 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-Nd69nX22P2bPjzNZWtr:b-8wn09i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does that work for you @stevenwarejones?
</blockquote></details>

I'd like documentation written how with best practices how to use any-sketch with all these params.


<!-- Sent from Reviewable.io -->

2023-08-30 18:55 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-Nd6mfvAEabJL1XrgGP5:b-6qw4q7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd like documentation written how with best practices how to use any-sketch with all these params.
</blockquote></details>

Just want to make sure my understanding is correct. Do you mean documenting recommended param values for the sketch based methodologies by adding comments in this file?


<!-- Sent from Reviewable.io -->

2023-08-30 19:45 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-Nd6yPhHDHy1y9rqix9X:bs82sx6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Just want to make sure my understanding is correct. Do you mean documenting recommended param values for the sketch based methodologies by adding comments in this file?
</blockquote></details>

I mean some markdown doc how to interact with this API - what params are put into any-sketch creation and what params are then send to this API.


<!-- Sent from Reviewable.io -->

2023-08-30 23:09 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-Nd7Rz-p3uQwNs2v4svg:bc1kqc7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I mean some markdown doc how to interact with this API - what params are put into any-sketch creation and what params are then send to this API.
</blockquote></details>

Would you mind if I ask what the goal is? Is a demonstration of generating sketches for direct measurements like [this code](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L858) what you're talking about? 

Note that the params used in the sketch generation is already demonstrated in `EdpSimulator` and `*.toSketchConfig()` in `SktechGenerator` [(see here for example)](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SketchGenerator.kt#L69). If someone wants to generate sketches for direct reach using `LiquidLegionsCountDistinct`, they can add a `LiquidLegionsCountDistinct.toSketchConfig()`, and the rest should be the same as before.

For what params are sent back to this API, it's already defined in `Measurement.Result`.


<!-- Sent from Reviewable.io -->

2023-08-31 20:46 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NdCL0li6gxPNE5vokYN:b-t0laab) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would you mind if I ask what the goal is? Is a demonstration of generating sketches for direct measurements like [this code](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L858) what you're talking about? 

Note that the params used in the sketch generation is already demonstrated in `EdpSimulator` and `*.toSketchConfig()` in `SktechGenerator` [(see here for example)](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SketchGenerator.kt#L69). If someone wants to generate sketches for direct reach using `LiquidLegionsCountDistinct`, they can add a `LiquidLegionsCountDistinct.toSketchConfig()`, and the rest should be the same as before.

For what params are sent back to this API, it's already defined in `Measurement.Result`.
</blockquote></details>

This seems like a larger piece of an EDP integration guide, which is obviously lacking. A oneof markdown doc isn't really the right way to approach this IMO. 


<!-- Sent from Reviewable.io -->

2023-08-31 22:33 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NdChr-iAUG6bpOyZEDK:b12s2z4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This seems like a larger piece of an EDP integration guide, which is obviously lacking. A oneof markdown doc isn't really the right way to approach this IMO.
</blockquote></details>

Sounds good to me. That will be a separate work from this PR, so if there is nothing else I will go merge the PR. @stevenwarejones does that work for you?


<!-- Sent from Reviewable.io -->

2023-09-01 17:06 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto` line 56 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/163#-NcbpmZV5JEiZQOoIoE5:-NdGhOFW2yVrrEvkTz_D:bb7m07t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f04a98a7143e62b7a95adb25cb1d77868f73d6a4/src/main/proto/wfa/measurement/api/v2alpha/direct_computation.proto#L56)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Sounds good to me. That will be a separate work from this PR, so if there is nothing else I will go merge the PR. @stevenwarejones does that work for you?
</blockquote></details>

okay


<!-- Sent from Reviewable.io -->

2023-09-01 17:17 UTC, merged