Add custom methodology with variance field
world-federation-of-advertisers/cross-media-measurement-api pull request #172
Opened 2023-09-15 22:32 UTC by riemanli

2023-09-15 22:32 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)
<!-- Reviewable:end -->

2023-09-15 22:32 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #172** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement-api/172" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement-api/172?utm_source=stack-comment).

2023-09-15 22:42 UTC, kungfucraig approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-15 22:42 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeQ-eL8CAkBsNziki8y:-NeQ-eL8CAkBsNziki8z:bweqdzt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L144)):*
> ```proto
>     // Used when data provider wants to use a methodology that is not listed in
>     // protocol config to compute direct measurements.
>     CustomDirectMethodology custom_direct_methodology = 2;
> ```

I don't think we should be renumbering fields here.


<!-- Sent from Reviewable.io -->

2023-09-15 22:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeQ-eL8CAkBsNziki8y:-NeQ-ywY826RLln6rdb2:b-yoxhxz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L144)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think we should be renumbering fields here.
</blockquote></details>

To my knowledge, all fields in `Direct` are newly added and not in any official release yet. It shouldn't have any problem, right?


<!-- Sent from Reviewable.io -->

2023-09-15 23:14 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeQ-eL8CAkBsNziki8y:-NeQ6jYJEk3uIOuoNgi8:bp18gv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L144)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

To my knowledge, all fields in `Direct` are newly added and not in any official release yet. It shouldn't have any problem, right?
</blockquote></details>

I'd have to look at the diffs to be sure, but I'll trust you. :) If this is all new, then it's fine.


<!-- Sent from Reviewable.io -->

2023-09-15 23:14 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-15 23:23 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeQ-eL8CAkBsNziki8y:-NeQ8dkjEuHQNuGGIOcd:bqppwkq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L144)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'd have to look at the diffs to be sure, but I'll trust you. :) If this is all new, then it's fine.
</blockquote></details>

Allow me to back up myself with some evidence https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/163.


<!-- Sent from Reviewable.io -->

2023-09-18 15:58 UTC, SanjayVas requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NeczANrDZUFZbySXrlF:bq10bzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
> ```proto
>       //
>       // Currently, only direct measurement would populate it. For backward
>       // compatibility, CustomDirectMethodology will be set with variance == NaN
> ```

AFAIK, protobuf has no way to indicate `NaN`.

More broadly, the change here is that methodology currently isn't required and therefore if it's unspecific the methodology (and therefore the variance) are unknown. The real backwards-compatibility here is that "custom" is supported in the protocol config, meaning an EDP may use a methodology that isn't one of the predefined ones. Right now they don't need to specify their methodology, but in the future they will need to. If they specify custom, then they will need to specify their variance.



_Code quote:_
```proto
variance == NaN
```


<!-- Sent from Reviewable.io -->

2023-09-18 19:04 UTC, stevenwarejones reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NedfHB2-s5FiZCtUTZ5:bu71jlg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

AFAIK, protobuf has no way to indicate `NaN`.

More broadly, the change here is that methodology currently isn't required and therefore if it's unspecific the methodology (and therefore the variance) are unknown. The real backwards-compatibility here is that "custom" is supported in the protocol config, meaning an EDP may use a methodology that isn't one of the predefined ones. Right now they don't need to specify their methodology, but in the future they will need to. If they specify custom, then they will need to specify their variance.
</blockquote></details>

Looks like protobuf can use Kotlin.float.NaN or parse Json "infinity", "NaN", etc. Wouldn't that work @SanjayVas ?


<!-- Sent from Reviewable.io -->

2023-09-18 19:31 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NedlN_DECHdIRLCV9-1:b-mk6dw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Looks like protobuf can use Kotlin.float.NaN or parse Json "infinity", "NaN", etc. Wouldn't that work @SanjayVas ?
</blockquote></details>

I like the use of NaN as a default value if Custom is the default methodology. Default of custom with zero as the default will be bad. This means we can forward the variance all the way up to the Reporting API as "NaN" too.


<!-- Sent from Reviewable.io -->

2023-09-18 19:59 UTC, stevenwarejones reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-18 20:41 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-Nedz1su0ojKrUQGRrkv:b4a4oue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
I demonstrated the usage of `NaN` in the [implementation PR](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1226). 

> More broadly, the change here is that methodology currently isn't required and therefore if it's unspecific the methodology (and therefore the variance) are unknown. The real backwards-compatibility here is that "custom" is supported in the protocol config, meaning an EDP may use a methodology that isn't one of the predefined ones. Right now they don't need to specify their methodology, but in the future they will need to. If they specify custom, then they will need to specify their variance.

Just restate to make sure we are on the same page. Basically there are three scenarios covered by this change:
1. When an EDP wants to use a custom methodology.
2. When an EDP hasn't incorporate the mandatory field of methodology in result.
3. When requesting existing measurements that were created without methodology specified.

(2) essentially results in (3) and so is part of the case of backward compatibility.


<!-- Sent from Reviewable.io -->

2023-09-18 20:52 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-Nee31BsDtVtyYSGuwqC:bm5sax3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I demonstrated the usage of `NaN` in the [implementation PR](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1226). 

> More broadly, the change here is that methodology currently isn't required and therefore if it's unspecific the methodology (and therefore the variance) are unknown. The real backwards-compatibility here is that "custom" is supported in the protocol config, meaning an EDP may use a methodology that isn't one of the predefined ones. Right now they don't need to specify their methodology, but in the future they will need to. If they specify custom, then they will need to specify their variance.

Just restate to make sure we are on the same page. Basically there are three scenarios covered by this change:
1. When an EDP wants to use a custom methodology.
2. When an EDP hasn't incorporate the mandatory field of methodology in result.
3. When requesting existing measurements that were created without methodology specified.

(2) essentially results in (3) and so is part of the case of backward compatibility.
</blockquote></details>

Yes, that's my understanding.


<!-- Sent from Reviewable.io -->

2023-09-18 22:04 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-19 17:16 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NeiPWOhDBA-GaIeF6hO:b-bye5v5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
> I like the use of NaN as a default value if Custom is the default methodology.

I disagree. I think we just shouldn't have a default here. To clarify, the crux of the issue was that we have an invariant that must not be violated: all participants **must** follow the ProtocolConfig. The state prior to this PR was that

1. We only supported a strict set of predefined methodologies in ProtocolConfig
2. We assumed a methodology if the EDP did not specify one (i.e. we had a default in Measurement.Result).

The state I expect after this PR, given our previous discussion:

1. We support an additional methodology that's not predefined (i.e. "custom")
2. There is no default in Measurement.Result. If the EDP doesn't specify anything, the methodology is unknown.
    * In a future release, the EDP will be required to specify a methodology


<!-- Sent from Reviewable.io -->

2023-09-19 17:53 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NeiX8SU2br4I1fQ-Ywh:b3fcsk6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
> There is no default in Measurement.Result. If the EDP doesn't specify anything, the methodology is unknown.

I thought we were trying to solve the issue of using incorrect defaults (deterministic count etc) by making custom methodology the default. It seems like you want no default at all and allow unspecified before mandating direct methodology field.


<!-- Sent from Reviewable.io -->

2023-09-19 17:53 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NeiZtge8vZFBVS_mEYV:b2pfto9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I like the use of NaN as a default value if Custom is the default methodology.

I disagree. I think we just shouldn't have a default here. To clarify, the crux of the issue was that we have an invariant that must not be violated: all participants **must** follow the ProtocolConfig. The state prior to this PR was that

1. We only supported a strict set of predefined methodologies in ProtocolConfig
2. We assumed a methodology if the EDP did not specify one (i.e. we had a default in Measurement.Result).

The state I expect after this PR, given our previous discussion:

1. We support an additional methodology that's not predefined (i.e. "custom")
2. There is no default in Measurement.Result. If the EDP doesn't specify anything, the methodology is unknown.
    * In a future release, the EDP will be required to specify a methodology
</blockquote></details>

I'm fine with the proposal from @SanjayVas 


<!-- Sent from Reviewable.io -->

2023-09-19 18:05 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-NeiayE-6FTxSjDXZFNS:b1buofy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
> I thought we were trying to solve the issue of using incorrect defaults (deterministic count etc) by making custom methodology the default. It seems like you want no default at all and allow unspecified before mandating direct methodology field.

We're trying to solve the fact that we put ourselves in a situation where the EDP couldn't always satisfy the invariant w.r.t. ProtocolConfig. The previous assumption of a default was derived from the assumption that the EDP would be using one of our predefined methodologies.


<!-- Sent from Reviewable.io -->

2023-09-19 20:27 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-Nej65ZZ3yYKmxegu-Q_:b-kas453) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I thought we were trying to solve the issue of using incorrect defaults (deterministic count etc) by making custom methodology the default. It seems like you want no default at all and allow unspecified before mandating direct methodology field.

We're trying to solve the fact that we put ourselves in a situation where the EDP couldn't always satisfy the invariant w.r.t. ProtocolConfig. The previous assumption of a default was derived from the assumption that the EDP would be using one of our predefined methodologies.
</blockquote></details>

If we don't have a default here, the upstream variance calculator is going to have to assume something when it doesn't find a methodology. We can certainly assume a default there instead of here, but unless we are going to change the ReportV2 API to make those fields optional we're probably stuck writing NaN as the variance.

FWIW, I think any of these options are fine given that we want to quickly transition to these methodology fields being required.


<!-- Sent from Reviewable.io -->

2023-09-20 03:39 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 177 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-NeczANq3fo2aKn07Zzr:-Neiheib12uwEZaWiRYN:bkbdvzg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ae512309d28628369866eb4b3ca78c0f29c5e0bd/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L177)):*
After an offline discussion with Sanjay, I would like to do the following:
1. Direct methodology:
    * Before the field is set to be required: Allow unspecified for all measurements.
    * After: Document the field is required for new fulfillments, but it may not be set for legacy measurements.

    In both case, the user of measurements needs to determine what to do when the field is unspecified. For Reporting V2, as Craig said, we need to document the behavior.
>
2. Direct noise mechanism: same strategy

Please see the latest change.


<!-- Sent from Reviewable.io -->

2023-09-20 12:48 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-20 14:56 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-20 15:07 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 268 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-Nen7SFJ2G56Thjk8fS8:-Nen7SFJ2G56Thjk8fS9:be1rxmm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ca9517d3cd50b4e01742e6d9eb2f6fc15033000f/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L268)):*
> ```proto
>       oneof methodology {
>         // Custom methodology.
>         CustomDirectMethodology custom_direct_methodology = 3;
> ```

I don't think this applies to population. @stevenwarejones WDYT?


<!-- Sent from Reviewable.io -->

2023-09-20 16:13 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-09-20 18:43 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 268 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-Nen7SFJ2G56Thjk8fS8:-NentRkzCIbgcSWFlU3y:be4wkv8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ca9517d3cd50b4e01742e6d9eb2f6fc15033000f/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L268)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think this applies to population. @stevenwarejones WDYT?
</blockquote></details>

I'm not aware of a non-deterministic approach that we've approved. It does raise the question if a population data provider should provide some sort of variance. But I'd just delete it for now.


<!-- Sent from Reviewable.io -->

2023-09-20 20:46 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 268 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172#-Nen7SFJ2G56Thjk8fS8:-NeoL6gV1B-mfwqZs8IW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ca9517d3cd50b4e01742e6d9eb2f6fc15033000f/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L268)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not aware of a non-deterministic approach that we've approved. It does raise the question if a population data provider should provide some sort of variance. But I'd just delete it for now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-20 21:53 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-20 21:55 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-09-21 13:44 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-09-21 15:00 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-09-21 16:22 UTC, merged