Change type of exchange_workflow field in RecurringExchange.
world-federation-of-advertisers/cross-media-measurement-api pull request #183
Opened 2023-10-13 18:13 UTC by SanjayVas

This resource type is not used by any service so this is a safe change.

Closes #182

2023-10-13 18:13 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)
<!-- Reviewable:end -->

2023-10-14 02:10 UTC, stevenwarejones requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183#-Ngfwa71EE1K2tA4lqo9:-Ngfwa71EE1K2tA4lqoA:bn75i9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c8bfdd90d8651912b7d176ef11379a6cfc5de336/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L45)):*
> ```proto
> 
>   // Serialized `ExchangeWorkflow` for this `RecurringExchange`.
>   bytes exchange_workflow = 2 [
> ```

Shouldn't you deprecate the old field and add a new?


<!-- Sent from Reviewable.io -->

2023-10-16 15:06 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183#-Ngfwa71EE1K2tA4lqo9:-Ngt-gWpECiVcNEkvTmz:bnck3am) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c8bfdd90d8651912b7d176ef11379a6cfc5de336/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L45)):*
As indicated in the PR description:

> This resource type is not used by any service so this is a safe change.

This resource has never been returned by any service, so we're free to make backwards-incompatible changes. Of course we should eventually have Get and List methods for every resource.


<!-- Sent from Reviewable.io -->

2023-10-16 15:21 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183#-Ngfwa71EE1K2tA4lqo9:-Ngt3Teq8Tq_f9ZBu0q8:b38mqta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c8bfdd90d8651912b7d176ef11379a6cfc5de336/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As indicated in the PR description:

> This resource type is not used by any service so this is a safe change.

This resource has never been returned by any service, so we're free to make backwards-incompatible changes. Of course we should eventually have Get and List methods for every resource.
</blockquote></details>

The name should be consistent with https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L73


<!-- Sent from Reviewable.io -->

2023-10-16 15:35 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183#-Ngfwa71EE1K2tA4lqo9:-Ngt6eo2Ac-pqo5AMUHL:bdzgu9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c8bfdd90d8651912b7d176ef11379a6cfc5de336/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The name should be consistent with https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L73
</blockquote></details>

Done (updated the field in ExchangeStep).

I had thought of that too, but had been avoiding the disruption. That said, we're making other breaking changes to the exchange API in this version anyway and the rename is wire-compatible change.

Note that renaming the field in *this* message would be inconsistent with any of our other serialized message fields which do not use the "serialized" prefix. I assume that ExchangeStep only had this prefix since the field in this message was not serialized.


<!-- Sent from Reviewable.io -->

2023-10-16 15:52 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto` line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183#-NgtAmh35UbvH4OVEehi:-NgtAmh35UbvH4OVEehj:bn5xzfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c8bfdd90d8651912b7d176ef11379a6cfc5de336/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L73)):*
> ```proto
>   // Denormalized `exchange_workflow` field from the ancestor
>   // `RecurringExchange`.
>   bytes serialized_exchange_workflow = 3 [
> ```

this field is read by clients today. That does make this a breaking change.


<!-- Sent from Reviewable.io -->

2023-10-16 16:01 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto` line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183#-NgtAmh35UbvH4OVEehi:-NgtC4ow519lCqfzNlX9:b-faby0h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c8bfdd90d8651912b7d176ef11379a6cfc5de336/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this field is read by clients today. That does make this a breaking change.
</blockquote></details>

"Breaking change" for API protobuf definition changes refers to wire-incompatible changes. A field rename for a gRPC-only API is fully wire compatible. (Note that this wouldn't be a backwards-compatible change if we also exposed this as a REST API, as that involves JSON serialization by field name).

This may result in changes to generated language-specific code that could result in compilation breakage, but that's a separate concern.


<!-- Sent from Reviewable.io -->

2023-10-16 20:17 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-11-01 16:59 UTC, closed without merging