Drop signatures for public key fields where not needed.
world-federation-of-advertisers/cross-media-measurement-api pull request #187
Opened 2023-10-24 18:59 UTC by SanjayVas

This is a breaking API change, but attempts to maintain wire-compatibility for EDP Requisition fulfillment.

2023-10-24 18:59 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187)
<!-- Reviewable:end -->

2023-10-31 22:48 UTC, SanjayVas commented
This is a follow-up to #185.

2023-11-01 13:47 UTC, stevenwarejones requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187#-NiA7k3dEqFRLaOc-Lve:-NiA7k3dEqFRLaOc-Lvf:buuu615) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3e7f276a7a578302d941ad03ebbe1ca7ed41095/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L78)):*
> ```proto
>       // (--
>       // TODO(world-federation-of-advertisers/cross-media-measurement-api#188):
>       // Remove this once the certificate is always specified in
> ```

you can remove this if you wait for PR 171 to merge first. wdyt?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187#-NiA7tIHBg2APy1qvcro:-NiA7tIHBg2APy1qvcrp:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3e7f276a7a578302d941ad03ebbe1ca7ed41095/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L84)):*
> ```proto
>   // Remove this once the certificate is always specified in
>   // `FulfillDirectRequisitionRequest`. --)
>   string data_provider_certificate = 6 [
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-11-06 19:46 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187#-NiA7k3dEqFRLaOc-Lve:-Nia9rRO0H6Oa8XgI-B4:bfm1nfz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/92e29126c519b05b36d7f65332e1491c0e4c8ad0/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you can remove this if you wait for PR 171 to merge first. wdyt?
</blockquote></details>

Not quite. The *always* part here is important, meaning all EDPs need to be specifying the new field.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187#-NiA7tIHBg2APy1qvcro:-NiaA0B48577z0mhMsZp:bs4q9op) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/92e29126c519b05b36d7f65332e1491c0e4c8ad0/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L84)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ditto.


<!-- Sent from Reviewable.io -->

2023-11-10 14:28 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-11-13 20:38 UTC, SanjayVas reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-11-13 20:39 UTC, merged