Drop free-form tags map from Measurement in favor of reference ID.
world-federation-of-advertisers/cross-media-measurement-api pull request #19
Opened 2021-04-29 17:55 UTC by SanjayVas

This provides a simpler idompotency mechanism for Measurement Consumers.

2021-04-29 21:13 UTC, kungfucraig requested changes

2021-04-29 21:13 UTC, kungfucraig commented on src/main/proto/wfa/measurement/api/v2alpha/measurement.proto
> +  // ID referencing the `Measurement` in an external system, provided by the
Can you mention this is being used as an idempotency key?

2021-04-30 17:54 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 146 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19#-MZTlQMBM9RyhbwHEpXw-r1-146:-MZYuf-PBAQzbN2Kypbw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1f92efe65dd2bff2da83dd5bac217341daa10d0e/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L146)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you mention this is being used as an idempotency key?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-30 18:19 UTC, uakyol approved these changes

2021-04-30 19:54 UTC, oliver-amzn approved these changes
⛵

2021-05-02 22:18 UTC, zachcwc approved these changes

2021-05-02 22:18 UTC, zachcwc commented on src/main/proto/wfa/measurement/api/v2alpha/measurement.proto
> +  string measurement_reference_id = 12;
Does this mean the tags map is offloaded to the MC front end?

2021-05-03 14:46 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @zachcwc)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19#-MZTlQMBM9RyhbwHEpXw-r2-152:-MZmfrry5JevAnk0vuSM:b-dta63e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/04fc587665d2ff776a096267df6f556acd0ac839/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L152)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Does this mean the tags map is offloaded to the MC front end?
</blockquote></details>

Yes, or more specifically any additional Measurement metadata.

In general, we want the Kingdom to know as little as possible.


<!-- Sent from Reviewable.io -->

2021-05-03 17:06 UTC, zachcwc reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19#-MZTlQMBM9RyhbwHEpXw-r2-152:-MZnAkMuBHDNjBBdx8pp:bm97qg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/04fc587665d2ff776a096267df6f556acd0ac839/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, or more specifically any additional Measurement metadata.

In general, we want the Kingdom to know as little as possible.
</blockquote></details>

Awesome makes sense, so now kingdom has no metadata about measurement requisitions except EDPs involved?


<!-- Sent from Reviewable.io -->

2021-05-03 17:16 UTC, zachcwc reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19#-MZTlQMBM9RyhbwHEpXw-r2-152:-MZnDktP247IXo8FPenu:b-odqrcm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/04fc587665d2ff776a096267df6f556acd0ac839/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L152)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Awesome makes sense, so now kingdom has no metadata about measurement requisitions except EDPs involved?
</blockquote></details>

Ah nevermind, they still have to know about the event groups right? So they know which event groups are available to take measurements over?


<!-- Sent from Reviewable.io -->

2021-05-03 17:22 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @zachcwc)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19#-MZTlQMBM9RyhbwHEpXw-r2-152:-MZnEvsZ1dqm48JoeNdf:b-bo1lod) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/04fc587665d2ff776a096267df6f556acd0ac839/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L152)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Ah nevermind, they still have to know about the event groups right? So they know which event groups are available to take measurements over?
</blockquote></details>

Nope, just the EDPs. The Event Groups are contained in the encrypted `RequisitionSpec`.


<!-- Sent from Reviewable.io -->

2021-05-03 17:28 UTC, zachcwc approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19#-MZTlQMBM9RyhbwHEpXw-r2-152:-MZnDygI5YC8qiz2I0us:b-7rx1gg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/04fc587665d2ff776a096267df6f556acd0ac839/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nope, just the EDPs. The Event Groups are contained in the encrypted `RequisitionSpec`.
</blockquote></details>

Ah right thanks!


<!-- Sent from Reviewable.io -->

2021-05-03 18:37 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/19)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-05-03 18:56 UTC, merged