Add data_provider_certificate into HMSS requisition fulfillment.
world-federation-of-advertisers/cross-media-measurement-api pull request #202
Opened 2024-02-27 20:10 UTC by renjiezh

Duchy needs the certificate specified by the EDP to verify the signature of secret seed.

2024-02-27 20:10 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)
<!-- Reviewable:end -->

2024-02-28 00:43 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202#-Nrh9YA6D_2NTealrAj4:-Nrh9YA6D_2NTealrAj5:bt9kk4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6bb724d5791dc86850913157b13db4b9742022b8/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L85)):*
> ```proto
>         (google.api.resource_reference).type = "halo.wfanet.org/Certificate",
>         (google.api.field_behavior) = OUTPUT_ONLY,
>         (google.api.field_behavior) = IMMUTABLE
> ```

This is a required input field.



_Suggestion:_
```proto
        (google.api.field_behavior) = REQUIRED
```


<!-- Sent from Reviewable.io -->

2024-02-28 00:49 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202#-Nrh9YA6D_2NTealrAj4:-NrhB2EV6BAxi5yJSMng:bu4ozr6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6bb724d5791dc86850913157b13db4b9742022b8/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a required input field.
</blockquote></details>

Done.
Thanks.


<!-- Sent from Reviewable.io -->

2024-02-28 01:11 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @ple13)



<!-- Sent from Reviewable.io -->

2024-02-28 15:05 UTC, ple13 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-02-28 21:10 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-02-29 20:53 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2024-02-29 22:11 UTC, merged