Add register_count into HMSS requisition fulfillment header.
world-federation-of-advertisers/cross-media-measurement-api pull request #203
Opened 2024-03-07 21:26 UTC by renjiezh

2024-03-07 21:26 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)
<!-- Reviewable:end -->

2024-03-07 21:32 UTC, kungfucraig requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 289 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203#-NsPoZsMDJZMl9m5dXoU:-NsPoZsMDJZMl9m5dXoV:bnrpw5e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1ade61f68f145202f479d9232af86755c9bdbeae/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L289)):*
> ```proto
> // Sketch parameters for a Honest Majority Shuffle Based Secret Sharing
> // protocol.
> message ShareShuffleSketchParams {
> ```

Do you think it's worth adding a comment about how the size of the sketch is arrived at? Something like:

"The size of the sketch is calculated by the EDP and is determined by the sampling interval and the size of the population being measured. It is expected that EDPs will calculate the length in exactly the same way. Support libraries are provided for this in the any-sketch repo."

@SanjayVas Wdyt?


<!-- Sent from Reviewable.io -->

2024-03-07 21:37 UTC, ple13 approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-03-08 19:08 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 289 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203#-NsPoZsMDJZMl9m5dXoU:-NsURc1eEOwy6kTBfP61:bisbumo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1ade61f68f145202f479d9232af86755c9bdbeae/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L289)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Do you think it's worth adding a comment about how the size of the sketch is arrived at? Something like:

"The size of the sketch is calculated by the EDP and is determined by the sampling interval and the size of the population being measured. It is expected that EDPs will calculate the length in exactly the same way. Support libraries are provided for this in the any-sketch repo."

@SanjayVas Wdyt?
</blockquote></details>

SGTM with two the slight modifications:

1. We don't use EDP abbreviation in the API and instead reference the `DataProvider` resource.
2. Instead of just mentioning support libraries are available, reference the library. e.g. "See foo::bar::Baz in the any-sketch library"
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 290 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203#-NsUSck10FGkddWc2dm6:-NsUSck10FGkddWc2dm7:b-yx56h8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1ade61f68f145202f479d9232af86755c9bdbeae/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L290)):*
> ```proto
> // protocol.
> message ShareShuffleSketchParams {
>   reserved 1;
> ```

You're technically safe to renumber in this case because this message has never been used in released code, but this is also fine.


<!-- Sent from Reviewable.io -->

2024-03-08 19:20 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 289 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203#-NsPoZsMDJZMl9m5dXoU:-NsUVBi_6p5BK9M2__Gu:botnjt9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1ade61f68f145202f479d9232af86755c9bdbeae/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L289)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

SGTM with two the slight modifications:

1. We don't use EDP abbreviation in the API and instead reference the `DataProvider` resource.
2. Instead of just mentioning support libraries are available, reference the library. e.g. "See foo::bar::Baz in the any-sketch library"
</blockquote></details>

Unfortunately said libraries do not exist yet, but maybe we can posit a directory to reference now? Might I suggest: https://github.com/world-federation-of-advertisers/any-sketch-java/tree/main/src/main/java/org/wfanet/hmss


<!-- Sent from Reviewable.io -->

2024-03-12 20:48 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 289 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203#-NsPoZsMDJZMl9m5dXoU:-NsoPn1H6Ep24kF7kRvg:b-pwb2tx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1ade61f68f145202f479d9232af86755c9bdbeae/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L289)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Unfortunately said libraries do not exist yet, but maybe we can posit a directory to reference now? Might I suggest: https://github.com/world-federation-of-advertisers/any-sketch-java/tree/main/src/main/java/org/wfanet/hmss
</blockquote></details>

Comment added on `register_count` in RequisitionFulfillmentRequest. I did not mention the library. It will be covered in rollout instruction doc.


<!-- Sent from Reviewable.io -->

2024-03-12 21:50 UTC, kungfucraig approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2024-03-13 16:13 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2024-03-13 17:32 UTC, merged