Add Population Spec and update documentation in related files.
world-federation-of-advertisers/cross-media-measurement-api pull request #206
Opened 2024-03-20 16:27 UTC by kungfucraig

Population Spec provides a way to specify ranges of VIDs and their related attributes. It is meant to be used as the format for the Population Blob defined by the Population resource.

2024-03-20 16:27 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)
<!-- Reviewable:end -->

2024-03-20 17:19 UTC, SanjayVas requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_template.proto` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtRpm8gB2GVFG3OJ-41:-NtRpm8gB2GVFG3OJ-42:bo1f9zj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/073d32bb783d87363291fa47f602923e6d6a2a9a/src/main/proto/wfa/measurement/api/v2alpha/event_template.proto#L27)):*
> ```proto
> // Template for an event message.
> message EventTemplate {
>   // The type URL of the Event Template.
> ```

This would be a breaking change. If you want to switch to type URL, add an additional field with a new tag number and deprecate the old one.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtRqRFG59XI7x7Z72KY:-NtRqRFG59XI7x7Z72KZ:b842lwz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/073d32bb783d87363291fa47f602923e6d6a2a9a/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L45)):*
> ```proto
>     //
>     // This field is required.
>     int64 vid_start = 1 [(google.api.field_behavior) = REQUIRED];
> ```

nit: I'd recommend splitting out the actual range message from the population fields. That structure has happened to be useful on its own, e.g. in synthetic event group specs. It may provide easier conversion.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtRr3fwBU3atx0bd2_Y:-NtRr3fx7sqndG2Ih0De:b-pqbjfw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/073d32bb783d87363291fa47f602923e6d6a2a9a/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L45)):*
> ```proto
>     //
>     // This field is required.
>     int64 vid_start = 1 [(google.api.field_behavior) = REQUIRED];
> ```

For consistency with other range/interval types used in this API.



_Suggestion:_
```proto
start_vid
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtRrAGu-KIeMLFtkAzp:-NtRrAGu-KIeMLFtkAzq:b-ej9h46) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/073d32bb783d87363291fa47f602923e6d6a2a9a/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L51)):*
> ```proto
>     // In the case the range specifies a single VID, vid_end
>     // will be the same as vid_start.
>     int64 vid_end = 2 [(google.api.field_behavior) = REQUIRED];
> ```

nit: The other range/intervals in this API have an exclusive end, so I'd recommend having the "inclusive" part be explicit here.



_Suggestion:_
```proto
end_vid_inclusive
```


<!-- Sent from Reviewable.io -->

2024-03-20 19:28 UTC, SanjayVas approved these changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_template.proto` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtSJR6g4K6cdALRpu9u:-NtSJR6h8yimoeppphg7:b-767k5o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/deba53b72b3d83871b158a520ed1a1767a088f00/src/main/proto/wfa/measurement/api/v2alpha/event_template.proto#L29)):*
> ```proto
>   // The type of the Event Template. A fully-qualified protobuf message type.
>   //
>   // Note that the type URL for a given message name in a given
> ```

nit: I think this comment is somewhat confusing and unnecessary. The fact that this happens to be the latter part of a type URL is irrelevant. If you really want people to avoid mixing up the fully-qualified message type and the type URL, just add a note that this is not a type URL (though that *should* be obvious since this field is not named `type_url` like every other field containing a type URL and the description otherwise says nothing about a URL).


<!-- Sent from Reviewable.io -->

2024-03-20 19:36 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_template.proto` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtSJR6g4K6cdALRpu9u:-NtSKhq51Z9ypBq1bVvJ:bjw6bma) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/deba53b72b3d83871b158a520ed1a1767a088f00/src/main/proto/wfa/measurement/api/v2alpha/event_template.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I think this comment is somewhat confusing and unnecessary. The fact that this happens to be the latter part of a type URL is irrelevant. If you really want people to avoid mixing up the fully-qualified message type and the type URL, just add a note that this is not a type URL (though that *should* be obvious since this field is not named `type_url` like every other field containing a type URL and the description otherwise says nothing about a URL).
</blockquote></details>

This is still misleading, IMO. For one, it may give the impression that `_packagename_` is a single name without dotr separators.

"Fully-qualified type name" is a well-known concept (existing in languages like Java and C++ as well), and is in fact referenced in the canonical documentation for type URLs: https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/any.proto#L129


<!-- Sent from Reviewable.io -->

2024-03-22 20:33 UTC, stevenwarejones reviewed
do you have a notebook how this will be used in the new protocol?

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-:-NtbrVeg1DYZgXCZuHsD:b-rrbdu)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-03-22 21:15 UTC, kungfucraig reviewed
The notebook shows how to deal with the population and build the sketch. It doesn't use this proto.

I am going to start working on EDP libraries for building the sketch. Happy to revise this as we proceed with that.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-:-Ntc05COCqGhgSSEQLu8:b-ig5qv4)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-03-22 21:34 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 59 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-Ntc3sjR7s1C6XlAfeuf:-Ntc3sjR7s1C6XlAfeug:b-uc10fw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8c9600750944b38f33c9d0224c7038fafda4e218/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L59)):*
> ```proto
>     // Population.population_fields[0] specifies
>     // the type for VirtualPersonRange.population_field_values[0].
>     repeated PopulationFieldValue population_field_values = 3
> ```

Some ranges might be buckets of different fields. For example, 
1. Range 1: Male, 25-55
2. Range 2: Female, 25-55
3. Range 3: Everyone else


<!-- Sent from Reviewable.io -->

2024-03-22 23:08 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 59 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-Ntc3sjR7s1C6XlAfeuf:-NtcPJD49Ik0Ni2SGbmz:bp8jafa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8c9600750944b38f33c9d0224c7038fafda4e218/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L59)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Some ranges might be buckets of different fields. For example, 
1. Range 1: Male, 25-55
2. Range 2: Female, 25-55
3. Range 3: Everyone else
</blockquote></details>

I think in this case the EventTemplate enum that defines the dimension (e.g. Age) should reflect that since the VIDs themselves must be labeled from the valid values for the dimension in question.

See the examples at the bottom of this doc: https://docs.google.com/document/d/1TwzhtRmRqD8Fu_ziamG8kuIDQ4h4g3AMeKVUT4ilkM4/edit?tab=t.0

Or maybe I don't understand your concern.


<!-- Sent from Reviewable.io -->

2024-03-25 21:43 UTC, kungfucraig reviewed
@SanjayVas @stevenwarejones I updated this based upon our discussion this morning. PTAL.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-:-NtrZKmr-o-9ICb6vRdm:b-ohq6gq)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-03-25 22:41 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-Ntrj9vZ7ZwewFYZ5fGW:-Ntrj9vZ7ZwewFYZ5fGX:b-d4s6e2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L29)):*
> ```proto
> // Specification for a `Population`. Immutable.
> message PopulationSpec {
>   // A range of Virtual Persons.
> ```

nit: define VID



_Suggestion:_
```proto
A range of Virtual Person IDs (VIDs)
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtriiunA9cJLQGLPGlL:-NtriiunA9cJLQGLPGlM:b-2zel5v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L39)):*
> ```proto
>     //
>     // In the case the range specifies a single VID, vid_end
>     // will be the same as vid_start.
> ```

Update comment to match field rename.



_Suggestion:_
```proto
    // If this has the same value as `start_vid`, then the range contains exactly one `VID`.
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-Ntrifj3Ba-Sx93WwQJt:-Ntrifj3Ba-Sx93WwQJu:b-z2fz0d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L45)):*
> ```proto
>   // A Subpopulation of the population defined by the PopulationSpec.
>   //
>   // A Subpopulation is composed of a set of VirtualPersonRanges,
> ```

nit: References to protobuf symbols in comments should be wrapped in backticks



_Suggestion:_
```proto
`VirtualPersonRange`s
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-Ntrhub5D7DIWT2Iz6Pk:-Ntrhub6ACIIoYJNXZC8:b-i410x2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L47)):*
> ```proto
>   // A Subpopulation is composed of a set of VirtualPersonRanges,
>   // all of which share the same attributes.
>   message Subpopulation {
> ```

nit: naming to match "sub-population" (see [`SyntheticPopulationSpec`](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto))



_Suggestion:_
```proto
SubPopulation
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 53 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtrjYqe9GzJ9UQ33krG:-NtrjYqf3XMcBuLzkaqo:byspoz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L53)):*
> ```proto
>     // an EventTemplate is a message annotated as such.
>     // See:
>     // https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto
> ```

Can be more accurate and concise here. The `EventTemplateDescriptor` type is defined in this package in this repo, so no need to link it.



_Suggestion:_
```proto
    // The `type_url` of each element must correspond to a known message type annotated with the `EventTemplateDescriptor` message option.
```


<!-- Sent from Reviewable.io -->

2024-03-25 23:06 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtriiunA9cJLQGLPGlL:-NtrpgQgDV-LxE_B4GJ0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update comment to match field rename.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto` line 53 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206#-NtrjYqe9GzJ9UQ33krG:-Ntrqllo5-lNyAqmzviw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5ef6afc4bf9918a1b3b9a4e6f6bb4006564e4c5/src/main/proto/wfa/measurement/api/v2alpha/population_spec.proto#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can be more accurate and concise here. The `EventTemplateDescriptor` type is defined in this package in this repo, so no need to link it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 23:37 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/206)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-03-26 17:58 UTC, merged

2024-04-08 22:06 UTC, SanjayVas commented
This introduced a new build warning:

```
wfa/measurement/api/v2alpha/population_spec.proto:21:1: warning: Import wfa/measurement/api/v2alpha/event_template.proto is unused
```

2024-04-08 22:19 UTC, kungfucraig commented
I'll fix it. Give me a couple days.