Add MPC methodologies to Reach and Frequency result.
world-federation-of-advertisers/cross-media-measurement-api pull request #209
Opened 2024-07-11 15:02 UTC by ple13

2024-07-11 15:02 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)
<!-- Reviewable:end -->

2024-07-11 20:57 UTC, renjiezh approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-07-11 22:21 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1YsR8t2Y4CyOsU5llI:-O1YsR8uDMIlMYjKMETy:b9n9f7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0902d20125cf51f7d193ecff154b5989e22512a3/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L157)):*
> ```proto
>       ProtocolConfig.NoiseMechanism noise_mechanism = 2;
> 
>       // The computation methodology done by data provider.
> ```

This is no longer accurate



_Code quote:_
```proto
 done by data provider
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1YsVXO0cFVC9f-1eHc:-O1YsVXO0cFVC9f-1eHd:b-w3walf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0902d20125cf51f7d193ecff154b5989e22512a3/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L160)):*
> ```proto
>       //
>       // Currently, only direct measurement and measurement via honest majority
>       // share shuffle protocol would populate it. During the transition of
> ```

We fully control this, so this should work for LLv2 out of the box.

The transition period is only for EDPs going between API versions.



_Code quote:_
```proto
      // Currently, only direct measurement and measurement via honest majority
      // share shuffle protocol would populate it. During the transition of
```


<!-- Sent from Reviewable.io -->

2024-07-12 05:22 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1YsR8t2Y4CyOsU5llI:-O1_NflqCzvmKfqIPV_1:b-d4hq75) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0902d20125cf51f7d193ecff154b5989e22512a3/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is no longer accurate
</blockquote></details>

I've updated the text.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement.proto` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1YsVXO0cFVC9f-1eHc:-O1_NhZd8PdTYI9oOd_I:b-d4hq75) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0902d20125cf51f7d193ecff154b5989e22512a3/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We fully control this, so this should work for LLv2 out of the box.

The transition period is only for EDPs going between API versions.
</blockquote></details>

I've updated the text.


<!-- Sent from Reviewable.io -->

2024-07-12 16:38 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1bnNbZ4FG4mQ2wUbBy:-O1bnNbZ4FG4mQ2wUbBz:b-6svadt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/34bdb93d7ae431598e414f9b5030ecba0306ee59/src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto#L1)):*
> ```proto
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

nit: maybe name this file `multi_party_computation.proto` to parallel `direct_computation.proto`?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1bnKonBTYXkfCT2iIX:-O1bnKonBTYXkfCT2iIY:by9q9sq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/34bdb93d7ae431598e414f9b5030ecba0306ee59/src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto#L20)):*
> ```proto
> 
> import "google/api/field_behavior.proto";
> import "wfa/measurement/api/v2alpha/protocol_config.proto";
> ```

Note that the methodology messages should only contain information that needs to be sent from the party  that sets the Measurement result. Anything that is already in the ProtocolConfig should not be duplicated in a methodology message.

Don't forget to also drop the dep in the BUILD target when dropping this import.


<!-- Sent from Reviewable.io -->

2024-07-12 16:54 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1bnNbZ4FG4mQ2wUbBy:-O1bpv-r5FuDdzjpQM-n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/34bdb93d7ae431598e414f9b5030ecba0306ee59/src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe name this file `multi_party_computation.proto` to parallel `direct_computation.proto`?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1bnKonBTYXkfCT2iIX:-O1bpvpKC0O7FeFP2FgA:b-kpfec2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/34bdb93d7ae431598e414f9b5030ecba0306ee59/src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that the methodology messages should only contain information that needs to be sent from the party  that sets the Measurement result. Anything that is already in the ProtocolConfig should not be duplicated in a methodology message.

Don't forget to also drop the dep in the BUILD target when dropping this import.
</blockquote></details>

Thanks. In this case, we won't need the (ro-)llv2 methodology as the config has all the information the MC needs.


<!-- Sent from Reviewable.io -->

2024-07-12 21:15 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1bnKonBTYXkfCT2iIX:-O1cnDOW1ZF6NwUvJF_L:b-9g3eh1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/34bdb93d7ae431598e414f9b5030ecba0306ee59/src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto#L20)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Thanks. In this case, we won't need the (ro-)llv2 methodology as the config has all the information the MC needs.
</blockquote></details>

We should still have them as empty messages so that we can eventually list the methodology oneof as required.


<!-- Sent from Reviewable.io -->

2024-07-15 14:14 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209#-O1bnKonBTYXkfCT2iIX:-O1qj01T2eIPF6lyRvax:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/34bdb93d7ae431598e414f9b5030ecba0306ee59/src/main/proto/wfa/measurement/api/v2alpha/mpc_protocol.proto#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We should still have them as empty messages so that we can eventually list the methodology oneof as required.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 17:11 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2024-07-15 19:54 UTC, stevenwarejones approved these changes
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/209)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2024-07-15 19:56 UTC, merged