Allow vid sampling interval wrapping around 0.
world-federation-of-advertisers/cross-media-measurement-api pull request #211
Opened 2024-07-24 18:05 UTC by renjiezh

2024-07-24 18:05 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211)
<!-- Reviewable:end -->

2025-04-21 20:30 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2025-04-25 17:42 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2025-04-26 00:00 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211#-OOjOK5CCgP25gWMFaS2:-OOjOK5CCgP25gWMFaS3:bom3f4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/84cb26ce7286b63323aa3ec9f82a7bc8354b6de4/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L58)):*
> ```proto
>   // Specifies a range of VIDs to be sampled.
>   //
>   // The interval is within range of [0.0, 1.0]. When interval wrapping is
> ```

i thought interval wrapping is only supported for hmms and not llv2 at the moment


<!-- Sent from Reviewable.io -->

2025-04-26 00:03 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211#-OOjOK5CCgP25gWMFaS2:-OOjOnJx34lgeiZ1xkZf:bboqjed) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/84cb26ce7286b63323aa3ec9f82a7bc8354b6de4/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i thought interval wrapping is only supported for hmms and not llv2 at the moment
</blockquote></details>

Yes, it is only for HMSS.


<!-- Sent from Reviewable.io -->

2025-04-26 00:05 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2025-05-27 19:42 UTC, merged