Add WITHDRAWN state to Requisition.
world-federation-of-advertisers/cross-media-measurement-api pull request #212
Opened 2024-08-09 17:25 UTC by SanjayVas

2024-08-09 17:25 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212)
<!-- Reviewable:end -->

2024-08-12 13:51 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212#-O45qMWr1-h6kCB1YJk7:-O45qMWsDz5KGSwgefEF:b-gwq2to) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1af267063ba07892b1651339dce3fdf8c02c3f2f/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L187)):*
> ```proto
>     // `measurement` will be in the `FAILED` state.
>     REFUSED = 3;
>     // The `Requisition` has been withdrawn. Terminal state.
> ```

should this be 
```
The `Requisition` has been withdrawn by a party other than the `DataProvider`. Terminal State.
```
Also, this will mean that the `measurement` will be in the `FAILED` state, correct?


<!-- Sent from Reviewable.io -->

2024-08-12 13:54 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212#-O45qMWr1-h6kCB1YJk7:-O45rS4_AtScdPPldmhi:b-gotrvk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1af267063ba07892b1651339dce3fdf8c02c3f2f/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L187)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this be 
```
The `Requisition` has been withdrawn by a party other than the `DataProvider`. Terminal State.
```
Also, this will mean that the `measurement` will be in the `FAILED` state, correct?
</blockquote></details>

my wording makes an assumption that the operator may want the ability to withdraw. If we don't want to cover that use case for now, we could just comment that this means it was withdrawn by the MC.


<!-- Sent from Reviewable.io -->

2024-08-12 18:13 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212#-O45qMWr1-h6kCB1YJk7:-O46lWTW7MMGqD8GxowP:b-ivwz6t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1af267063ba07892b1651339dce3fdf8c02c3f2f/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L187)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

my wording makes an assumption that the operator may want the ability to withdraw. If we don't want to cover that use case for now, we could just comment that this means it was withdrawn by the MC.
</blockquote></details>

The existing wording is correct, IMO. The `DataProvider` cannot withdraw a Requisition themselves, as is apparent by the lack of a WithdrawRequisition method. They can instead refuse.

This intentionally does not enumerate all the conditions that can result in a Requisition being withdrawn. At the moment, this can happen any time the Measurement transitions to FAILED or CANCELLED. This is not limited to MC cancellation, and can include a different EDP refusing their Requisition, a Duchy indicating a failure, etc.


<!-- Sent from Reviewable.io -->

2024-08-14 02:35 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-08-14 16:41 UTC, SanjayVas reviewed
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/212)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-08-14 16:41 UTC, merged