Add dataProvider and update_time to Requisition
world-federation-of-advertisers/cross-media-measurement-api pull request #217
Opened 2024-10-02 20:47 UTC by roaminggypsy

These are needed for measurement prober metric (LastTerminalRequisitionTime) publication

LastTerminalRequisitionTime, will have an attribute “data provider” whose value is the name. The actual value of the metric will come from the update time of the requisition that is associated with the particular EDP for the most recently issued Measurement.

2024-10-02 20:48 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217)
<!-- Reviewable:end -->

2024-10-02 22:31 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @roaminggypsy)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 265 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217#-O8ELtNS-V7IE1MC52aY:-O8ELtNT-J1jU9mV01rt:b-83lmzl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6f9f36fec5d2d41b13a6d68a843904623b47ce55/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L265)):*
> ```proto
> 
>   // When the 'Requisition' was last updated.
>   google.protobuf.Timestamp update_time = 17
> ```

Isn't the next ID 16?



_Suggestion:_
```proto
16
```


<!-- Sent from Reviewable.io -->

2024-10-02 22:53 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 265 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217#-O8ELtNS-V7IE1MC52aY:-O8ER0leBAsPas7VxHTS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6f9f36fec5d2d41b13a6d68a843904623b47ce55/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L265)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't the next ID 16?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-02 23:34 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217#-O8EWbDd4b33tI8FBgMg:-O8EXRTp0Lm0GanhiqBw:b-7s0ftw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/45ef602f18463c972fd1204a5b90a9d632e7a2bc/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll need to update the BUILD target deps for this.
</blockquote></details>

Do you mean requisition_proto's deps in the BUILD file? I added the timestamp entry to it


<!-- Sent from Reviewable.io -->

2024-10-03 00:34 UTC, SanjayVas approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)



<!-- Sent from Reviewable.io -->

2024-10-03 04:32 UTC, merged