feat: Add ReportMetadata to MeasurementSpec
world-federation-of-advertisers/cross-media-measurement-api pull request #222
Opened 2024-12-19 23:28 UTC by kungfucraig

2024-12-19 23:28 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)
<!-- Reviewable:end -->

2024-12-20 00:20 UTC, SanjayVas approved these changes
Make sure you don't merge this until you have the corresponding PR in the main repo ready.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-:-OEWQzg6BC913uGrF1-1:b5a4tes)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 148 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OEWQdEZCDEBeWXlfCBj:-OEWQdEZCDEBeWXlfCBk:b-gc5o1a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c85f73cfd6c9441d547c2fc64f7a2ca71de93c8d/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L148)):*
> ```proto
>   ];
> 
>   // Provides the report and metric for which this Measurement was created
> ```

nit: Verb phrases are for methods, not fields.



_Suggestion:_
```proto
  // Metadata about the use of this `Measurement` in the Reporting system.
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OEWQmIqBvRZgQnqB47l:-OEWQmIqBvRZgQnqB47m:bd0j1p2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c85f73cfd6c9441d547c2fc64f7a2ca71de93c8d/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L149)):*
> ```proto
> 
>   // Provides the report and metric for which this Measurement was created
>   message ReportMetadata {
> ```

nit: Maybe rename for flexibility, since this is arguably just metadata from the Reporting system



_Suggestion:_
```proto
ReportingMetadata
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OEWQIWU8OFS_k8e3cdK:-OEWQIWV0aaakYA8um3e:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c85f73cfd6c9441d547c2fc64f7a2ca71de93c8d/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L150)):*
> ```proto
>   // Provides the report and metric for which this Measurement was created
>   message ReportMetadata {
>     // The Report
> ```

nit



_Suggestion:_
```proto
// Resource name of the `Report`.
```


<!-- Sent from Reviewable.io -->

2024-12-20 19:44 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 155 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OE_aDS71eyVZDGynHa7:-OE_aDS71eyVZDGynHa8:b-jdqkw4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5b0560b60ccd3ea2f8f956a7229504ee9cc98fca/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L155)):*
> ```proto
>       (google.api.field_behavior) = REQUIRED,
>       (google.api.field_behavior) = IMMUTABLE,
>       (google.api.resource_reference) = { type: "halo.wfanet.org/Report" }
> ```

what's the right way to inform that this is `halo.wfanet.org.reporting/Report`


<!-- Sent from Reviewable.io -->

2024-12-20 19:55 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 155 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OE_aDS71eyVZDGynHa7:-OE_cU282LvK0iMRRvuL:b3o7hsi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5b0560b60ccd3ea2f8f956a7229504ee9cc98fca/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L155)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what's the right way to inform that this is `halo.wfanet.org.reporting/Report`
</blockquote></details>

This is the right way to document the type, but I missed that the type listed here is actually incorrect. It should be `reporting.halo-cmm.org/Report`

Similarly, the Reporting metric type is `reporting.halo-cmm.org/Metric


<!-- Sent from Reviewable.io -->

2024-12-20 21:30 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 155 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OE_aDS71eyVZDGynHa7:-OE_yYzgCMaB8n1Oa8B4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5b0560b60ccd3ea2f8f956a7229504ee9cc98fca/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L155)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is the right way to document the type, but I missed that the type listed here is actually incorrect. It should be `reporting.halo-cmm.org/Report`

Similarly, the Reporting metric type is `reporting.halo-cmm.org/Metric
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-20 21:35 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-02 15:41 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 155 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222#-OE_aDS71eyVZDGynHa7:-OFbfSHv87hMZ0OJPY9S:b-6fgzli) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5b0560b60ccd3ea2f8f956a7229504ee9cc98fca/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L155)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this addresses the concern I had


<!-- Sent from Reviewable.io -->

2025-01-02 15:42 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/222)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2025-01-27 21:38 UTC, merged