Use ephemeral sender keys for hybrid encryption.
world-federation-of-advertisers/cross-media-measurement-api pull request #35
Opened 2021-07-07 19:15 UTC by SanjayVas

* Document that the sender's KEM public key is embedded in each encrypted value.
* Indicate which recipient public key is used for each encrypted value field.

2021-07-07 19:31 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35#-Me1RZgM79F34HlTzw01:-Me1RZgM79F34HlTzw02:b-unolap) (no related file):*
I don't 100% understand this change, do we have more details written down somewhere?

---


<!-- Sent from Reviewable.io -->

2021-07-07 21:05 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35#-Me1RZgM79F34HlTzw01:-Me1mHBnBa4mZ3lLUD0-:bvlqfrf) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't 100% understand this change, do we have more details written down somewhere?
</blockquote></details>

I added some more details to the commit message. There's additional context in https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/4#pullrequestreview-698420901

---


<!-- Sent from Reviewable.io -->

2021-07-08 11:13 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35#-:-Me4oUj79ipBrUSBNPXu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-11 20:56 UTC, stevenwarejones approved these changes
If I'm understanding, then the ephemeral public key is now included along the ciphertext, correct? Does that mean we are changing our protocol to align with ICIES instead of a more generic hybrid scheme?

Also, 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35#-:-MeAzknf-pZwRlAs0c05:b-twgn1x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-12 15:12 UTC, SanjayVas reviewed
> Does that mean we are changing our protocol to align with ICIES instead of a more generic hybrid scheme?

Correct.

> Also,

I think your comment got cut off.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/35#-:-MeQGW-x3ZEOOaEWSImw:b-fp4w3v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-16 22:01 UTC, merged