Include public key certificate in DataProvider and MeasurementConsumer.
world-federation-of-advertisers/cross-media-measurement-api pull request #37
Opened 2021-08-02 23:24 UTC by SanjayVas

The existing messages stated that the public key signature for these resources can be verified using the current *preferred* certificate, but this is not always true (e.g. if a higher-preference certificate gets added).

2021-08-03 16:13 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37#-MgBlUDA-BGwbqyE67R4:-MgBlUDA-BGwbqyE67R5:b-b8zfyq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5afd5837ea9322dcbe22bbf41bd762e6264b74d1/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L39)):*
> ```
> preferred_certificate
> ```
Got a little confused of these now.

when will `preferred_certificate` be used? Based on the comment, `certificate` is used for verifying this EDP signatures.

also when is the `preferred_certificate` set? now EDP doesn't provide a `preferred_certificate_der` when creating a data_provider. 


<!-- Sent from Reviewable.io -->

2021-08-03 16:23 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37#-MgBlUDA-BGwbqyE67R4:-MgBmyjo8V9d01n1qI4p:bdeqm9s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5afd5837ea9322dcbe22bbf41bd762e6264b74d1/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L39)):*
> when is the `preferred_certificate` set? now EDP doesn't provide a `preferred_certificate_der` when creating a data_provider.

It was always intended to be a computed field based on criteria defined in [the Certificates doc](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c954985a7e2e44b6a82c6039e61ae80137be6e9/docs/certificates.md). The only reason there's a DER field here is so that the EDP is required to have a cert on creation.

> when will `preferred_certificate` be used? 

We may not actually need the preferred cert field for EDP now that I think about it, since I think you'd always use the cert for the public key. Similarly for MCs, I believe you're always using the cert specified in the Measurement. Let me see about dropping those.


<!-- Sent from Reviewable.io -->

2021-08-03 19:24 UTC, kungfucraig reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37#-MgBlUDA-BGwbqyE67R4:-MgCTCMnEwKHdmnuSEc8:blngscf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5afd5837ea9322dcbe22bbf41bd762e6264b74d1/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> when is the `preferred_certificate` set? now EDP doesn't provide a `preferred_certificate_der` when creating a data_provider.

It was always intended to be a computed field based on criteria defined in [the Certificates doc](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c954985a7e2e44b6a82c6039e61ae80137be6e9/docs/certificates.md). The only reason there's a DER field here is so that the EDP is required to have a cert on creation.

> when will `preferred_certificate` be used? 

We may not actually need the preferred cert field for EDP now that I think about it, since I think you'd always use the cert for the public key. Similarly for MCs, I believe you're always using the cert specified in the Measurement. Let me see about dropping those.
</blockquote></details>

I've looked at PR. Will block on this comment being resolved.


<!-- Sent from Reviewable.io -->

2021-08-04 00:42 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37#-MgBlUDA-BGwbqyE67R4:-MgD_DnT6KJ3Nr8VLHU9:bf8sxbn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5afd5837ea9322dcbe22bbf41bd762e6264b74d1/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L39)):*
>> when will `preferred_certificate` be used?
> 
> We may not actually need the preferred cert field for EDP now that I think about it, since I think you'd always use the cert for the public key. Similarly for MCs, I believe you're always using the cert specified in the Measurement. Let me see about dropping those.

I remember now! It's to help the EDP or MC pick a cert when updating (rotating) the public key.

Let me rearrange this to drop the field from EDP/MC/Duchy, and instead have it be accessible using a resource ID alias from the certificates collection.


<!-- Sent from Reviewable.io -->

2021-08-04 01:04 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37#-MgBlUDA-BGwbqyE67R4:-MgD_8WtBNR9PDaFy8No:b-6lzsv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5afd5837ea9322dcbe22bbf41bd762e6264b74d1/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

>> when will `preferred_certificate` be used?
> 
> We may not actually need the preferred cert field for EDP now that I think about it, since I think you'd always use the cert for the public key. Similarly for MCs, I believe you're always using the cert specified in the Measurement. Let me see about dropping those.

I remember now! It's to help the EDP or MC pick a cert when updating (rotating) the public key.

Let me rearrange this to drop the field from EDP/MC/Duchy, and instead have it be accessible using a resource ID alias from the certificates collection.
</blockquote></details>

Done.

I ended up leaving the fields for Duchy in order to have a way to enforce that a Duchy always has at least one certificate.


<!-- Sent from Reviewable.io -->

2021-08-04 17:43 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-04 18:23 UTC, oliver-amzn approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-04 19:55 UTC, merged