Add identification to the exchange_workflows
world-federation-of-advertisers/cross-media-measurement-api pull request #48
Opened 2021-09-17 18:28 UTC by jonmolle

This allows a party to identify which trusted cert should be used to
validate inputs as well as where shared storage is located (while
keeping that location hidden from the Kingdom).

These ids are:

1. A storage salt. To keep the location of shared storage secret from the kingdom (in case bucket security was misconfigured) this provides a salt value unknown to the kingdom (being encrypted) that, when concatenated with the exchange date and the other two values below will make a bucket name that is highly unique and unlikely to have a collision.

Note that the hash output will have to be limited to legal names for S3 and GCS buckets, IE: <64 characters, lowercase letters, numbers, and dashes (but not the first or last character).

2 & 3. the names of the EDP and MP certs in the clientCerts bundle. This follows the pattern of how requisiton.proto does things. 

The cert names will allow us grab the right certs for each exchange step attempt from clientCerts to validate the exchange_workflow itself and shared inputs.

2021-09-17 20:20 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-MjpPfFX5-A2PHEO7pdt:bydv0v2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
> ```protobuf
>     // This should be randomly generated and of sufficient size to deter brute
>     // force attacks on a secure hash of the value.
>     bytes encrypted_storage_salt = 1;
> ```

I'm a little confused how this is encrypted and who is encrypting


<!-- Sent from Reviewable.io -->

2021-09-17 21:44 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-MjpfxroD28Ax17TIOaJ:b-793lgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm a little confused how this is encrypted and who is encrypting
</blockquote></details>

This should be encrypted with one of the party's private key. I went back and forth about adding a Party field to identify who did the encrypting or we hard-coding it to always be one of the EDP or MP. I guess if there's a shared symmetric key somewhere we could even do that, but I'd rather involve as few keys as possible to make rotating them less arduous. This should be passed pre-encrypted when creating the workflow (obviously, since it is part of the workflow which is signed by both parties).

Do you have a preference? Now that you mention it I think I'll tag which party encrypted the value and unless you have strong feelings.


<!-- Sent from Reviewable.io -->

2021-09-19 22:42 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk-8KWBEScCz5ZVTBHR:b-58nm9a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

This should be encrypted with one of the party's private key. I went back and forth about adding a Party field to identify who did the encrypting or we hard-coding it to always be one of the EDP or MP. I guess if there's a shared symmetric key somewhere we could even do that, but I'd rather involve as few keys as possible to make rotating them less arduous. This should be passed pre-encrypted when creating the workflow (obviously, since it is part of the workflow which is signed by both parties).

Do you have a preference? Now that you mention it I think I'll tag which party encrypted the value and unless you have strong feelings.
</blockquote></details>

@stevenwarejones @jonmolle can we do a dev connect about this? I'm wondering if 
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk-CcYi3XKvUUkdRgah:-Mk-CcYi3XKvUUkdRgai:b7t2se0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5b394e1e0bb6820ba806afee05ac72b482540df/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L101)):*
> ```protobuf
>   repeated Step steps = 1;
> 
>   message ExchangeIdentifiers {
> ```

Don't we also need some metadata about which storage system is used and maybe even a bucket prefix? (One might imagine that we'd want all buckets to have the format `COMMON_PREFIX + SHA256(storage_salt + date)`)
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk-D-2j3W8sVMgypdwV:-Mk-CbSu32qa-mueAlrU:b-f42pql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5b394e1e0bb6820ba806afee05ac72b482540df/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L102)):*
> ```protobuf
> 
>   message ExchangeIdentifiers {
>     // An encrypted salt for this exchange workflow that's used when computing
> ```

Should we consider the alternative where each exchange has some `shared_output` that just has the bucket name for the next exchange? Is that simpler?


<!-- Sent from Reviewable.io -->

2021-09-20 12:33 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk2BGf9-deghMQkxsak:b5ctx1g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@stevenwarejones @jonmolle can we do a dev connect about this? I'm wondering if 
</blockquote></details>

i'm open to dev connect. I'd also be open to them *each* providing a salt. You can just concat them in a specified order. Alternatively, we could make a salt exchange step using asymmetric crypto.


<!-- Sent from Reviewable.io -->

2021-09-20 15:34 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk2pscfAV4aLxHDxbfN:b-csk0lo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm open to dev connect. I'd also be open to them *each* providing a salt. You can just concat them in a specified order. Alternatively, we could make a salt exchange step using asymmetric crypto.
</blockquote></details>

@stevenwarejones wdyt about the idea in my other comment?


<!-- Sent from Reviewable.io -->

2021-09-20 16:33 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk32IKb-UeDiSqAyU2b:boovzx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@stevenwarejones wdyt about the idea in my other comment?
</blockquote></details>

Happy to have a dev connect. I actually like the idea of each party having a salt, there's no addition complexity cost there vs what I was doing here.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk-CcYi3XKvUUkdRgah:-Mk30wa3C6QGD1VyTzF_:b-9sqkfz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5b394e1e0bb6820ba806afee05ac72b482540df/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L101)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Don't we also need some metadata about which storage system is used and maybe even a bucket prefix? (One might imagine that we'd want all buckets to have the format `COMMON_PREFIX + SHA256(storage_salt + date)`)
</blockquote></details>

My plan is roughly for each storage system to have their own builder that uses (or doesn't) the salt in a way that makes sense. Like for a file path you have fewer restrictions than a cloud storage bucket name. 
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk-D-2j3W8sVMgypdwV:-Mk31ToW0oO7e7BBndAT:b-4zs5xa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d5b394e1e0bb6820ba806afee05ac72b482540df/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we consider the alternative where each exchange has some `shared_output` that just has the bucket name for the next exchange? Is that simpler?
</blockquote></details>

That was my first suggestion we discussed, actually. The difference is adding some "identification" code that reads that output to find the bucket name vs doing the calculation again. There are some pros and cons to both; since we validate our input, we'd need a file in the bucket (or other location) we created to actually read that is validated. Or custom code to ignore that input.

This logic has to happen somewhere (we need to pass the cert names regardless to know what to validate with) and is low impact enough to not worry about calculating multiple times.


<!-- Sent from Reviewable.io -->

2021-09-20 18:40 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk3VFR_4xrMkOpMlL1D:b-7njxg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Happy to have a dev connect. I actually like the idea of each party having a salt, there's no addition complexity cost there vs what I was doing here.
</blockquote></details>

not positive which idea in the other comment you are referring to @efoxepstein 

I like 2 salts


<!-- Sent from Reviewable.io -->

2021-09-20 20:58 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk4-2E_Cnua0xPRySLP:b-asqrkf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
Eli's comment was

> Should we consider the alternative where each exchange has some shared_output that just has the bucket name for the next exchange? Is that simpler?
 


<!-- Sent from Reviewable.io -->

2021-09-20 21:00 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk4-brn2B2Uhxp39Zd1:b-kcv5a9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Eli's comment was

> Should we consider the alternative where each exchange has some shared_output that just has the bucket name for the next exchange? Is that simpler?
 
</blockquote></details>

2 salts sounds fine?


<!-- Sent from Reviewable.io -->

2021-09-21 12:47 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-Mk7NxVFCC9K8uY6N4Ka:b9yz7e1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

2 salts sounds fine?
</blockquote></details>

I think it simplifies things to just have a salt exchange through the MC at the beginning of each new exchange. These salts wouldn't get stored in blob storage since the salts are used to negotiate the blob storage. Instead, the MC keeps encrypted versions (that it can't decrypt). Each party generates a salt, signs, and encrypts it with the other party's public key and submits it as an early exchange step.


<!-- Sent from Reviewable.io -->

2021-09-21 20:57 UTC, efoxepstein approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-22 19:52 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-22 20:03 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MjpPfFX5-A2PHEO7pds:-MkDvIAK1Gs3qqj1-3Is:bplbasf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27b4d1541bda716f397ee99556e02bb4a12a4813/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L107)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i guess this means we're moving to just exchanging salts as steps in the exchange workflow? Can you add that in this PR or add a TODO and do it in a follow-up?
</blockquote></details>

Since we're not going to have salts in the workflow, I'm just going to leave it out if that's okay. I have another PR that uses the recurring exchange id as a temporary salt with the intention to replace it asap. There is a TODO there.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk98X_j0TAYLY-W0USO:-MkDrfzxDyldB2pXTAB3:bpz4out) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/932ae32ee75cb755dd55cd574311d7e3d88e6566/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L127)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should just be `data_provider` I think and reference the `DataProvider`, not a specific cert, because the cert will rotate over time.
</blockquote></details>

Yes, following our discussion yesterday I've refactored this a bit
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 131 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk98dnLEyFG606uq2cx:-MkDrl6zEqaQPYUEuS4X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/932ae32ee75cb755dd55cd574311d7e3d88e6566/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L131)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 135 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-Mk98ejd1oEDTDsaJ757:-MkDrljw3dkDo-ne10VJ:bwt9a8c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/932ae32ee75cb755dd55cd574311d7e3d88e6566/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L135)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we also need details about what storage system it is?
</blockquote></details>

Yes, I was going to add that later, but probably best to do that now, done.


<!-- Sent from Reviewable.io -->

2021-09-22 20:54 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MkE4dhOB-NGVzkzatbt:-MkEH8PECClqaBGjlVjf:b9z0brw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ec69e37c301415415e6f9dfbda8ef6eb43286d17/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about url access like we're adding for workflows?
</blockquote></details>

Let's add it when we need it? I feel like at least for the MVP, we can restrict ourselves to these two storage types. I'd also be open to just dropping this field for now until we have a better idea of what we want?


<!-- Sent from Reviewable.io -->

2021-09-22 20:56 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MkEHvgP8LchAqzLnREI:-MkEHvgP8LchAqzLnREJ:b-ayftdi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ec69e37c301415415e6f9dfbda8ef6eb43286d17/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L134)):*
> ```protobuf
>   message ExchangeIdentifiers {
>     // Resource key of the Data Provider for the recurring exchange.
>     string data_provider = 2;
> ```

Add `      [(google.api.resource_reference).type = "halo.wfanet.org/DataProvider"];` annotation please
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MkEHz1b6i2jKxCA5IKI:-MkEHz1b6i2jKxCA5IKJ:b-lwmp19) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ec69e37c301415415e6f9dfbda8ef6eb43286d17/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L137)):*
> ```protobuf
> 
>     // Resource key of the Model Provider for the recurring exchange.
>     string model_provider = 3;
> ```

Add `      [(google.api.resource_reference).type = "halo.wfanet.org/ModeProvider"];` annotation please


<!-- Sent from Reviewable.io -->

2021-09-22 20:58 UTC, stevenwarejones approved these changes
I'm good once you take care of the annotations

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-:-MkEILXe8hPY_vLe8ft7:bn7021h)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-23 18:48 UTC, jonmolle reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-:-MkIvWSp--luGl9IE1tx:bb6un1j)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MkE4dhOB-NGVzkzatbt:-MkIvXWWBlzZewATXRnB:b-f05klt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ec69e37c301415415e6f9dfbda8ef6eb43286d17/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Let's add it when we need it? I feel like at least for the MVP, we can restrict ourselves to these two storage types. I'd also be open to just dropping this field for now until we have a better idea of what we want?
</blockquote></details>

I think adding new enums as-needed is useful and I'm using the field in the storage builder code
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MkEHvgP8LchAqzLnREI:-MkIvUkOA_dT3P1RbYpq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ec69e37c301415415e6f9dfbda8ef6eb43286d17/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L134)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add `      [(google.api.resource_reference).type = "halo.wfanet.org/DataProvider"];` annotation please
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48#-MkEHz1b6i2jKxCA5IKI:-MkIvV6Z295Uf8gFIPi9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ec69e37c301415415e6f9dfbda8ef6eb43286d17/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L137)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add `      [(google.api.resource_reference).type = "halo.wfanet.org/ModeProvider"];` annotation please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-23 18:50 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2021-09-23 18:51 UTC, merged